/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.sd.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.eclipse.emf.ecore.util.EcoreUtil
import org.eclipse.xtext.resource.XtextResource
import java.io.ByteArrayOutputStream
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl
import com.rm2pt.rapidood.sd.SequenceDiagramRuntimeModule
import com.rm2pt.rapidood.sd.SequenceDiagramStandaloneSetup
import org.eclipse.xtext.resource.IResourceFactory
import java.io.IOException
import com.rm2pt.rapidood.sd.sequenceDiagram.SequenceDiagram
import java.util.List
import org.eclipse.emf.ecore.EObject
import com.rm2pt.rapidood.sd.sequenceDiagram.MixEnd
import com.rm2pt.rapidood.sd.sequenceDiagram.Execution
import com.rm2pt.rapidood.sd.sequenceDiagram.ExecutionEnd
import com.rm2pt.rapidood.sd.sequenceDiagram.Activation
import com.rm2pt.rapidood.sd.sequenceDiagram.Message
import com.rm2pt.rapidood.sd.sequenceDiagram.ExecutionStart
import com.rm2pt.rapidood.sd.sequenceDiagram.MessageEnd
import com.rm2pt.rapidood.sd.sequenceDiagram.Deactivation
import com.rm2pt.rapidood.sd.sequenceDiagram.SequenceDiagramFactory
import java.util.HashMap
import java.util.Map
import java.util.ArrayList
import org.eclipse.xtext.resource.IResourceDescription
import java.util.Deque
import com.rm2pt.rapidood.sd.sequenceDiagram.Participant
import java.util.ArrayDeque
import com.google.inject.Inject
import org.eclipse.xtext.serializer.ISerializer
import java.util.Collections
import org.eclipse.xtext.resource.EObjectDescription
import com.rm2pt.rapidood.sd.sequenceDiagram.MultiContext

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class SequenceDiagramGenerator extends AbstractGenerator {

	static List<EObject> ends = new ArrayList()

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
//		fsa.generateFile('greetings.txt', 'People to greet: ' + 
//			resource.allContents
//				.filter(Greeting)
//				.map[name]
//				.join(', '))
		// 获取文件名
		val fileName = resource.URI.lastSegment()
		if (fileName.startsWith('enhanced_'))
			return;
		println('为文件' + fileName + '生成增强的序列图文件')
		val newFile = 'enhanced_' + fileName
		
		// 首先复制一份原始内容到新文件中
        val outputStream = new ByteArrayOutputStream()
        resource.save(outputStream, null)
        val contentAsString = outputStream.toString("UTF-8")
        val fileContent = contentAsString as CharSequence
		fsa.generateFile(newFile, fileContent)       
		
		val uri = fsa.getURI(newFile)	
		var resourceSet = new ResourceSetImpl()	
		val injector = new SequenceDiagramStandaloneSetup().createInjectorAndDoEMFRegistration()
		val IResourceFactory resourceFactory = injector.getInstance(IResourceFactory)
		resourceSet.resourceFactoryRegistry.extensionToFactoryMap.put('sd', resourceFactory)
		
		var newResource = resourceSet.getResource(uri, true);
		newResource.save(Collections.EMPTY_MAP)
		// 不需要把原来的所有元素深拷贝到现有Resource中，因为上面写入的文件已经被解析为相应的Resource了
		// newResource.contents.addAll(resource.contents.map[EcoreUtil.copy(it)])
		enhanceModel(newResource)
	}
	
	def void enhanceModel(Resource resource) {
		// 顺序图父元素
		var sd = resource.contents.get(0) as SequenceDiagram
		generateEnds(sd)
		generateExecutions(sd)

		try {
			resource.modified = true 
			
			resource.save(Collections.EMPTY_MAP)
			println('saved');
		} catch (IOException e) {
			println('filed to write');
		}
	}
	
	def void generateEnds(SequenceDiagram sd) {
		val allContents = sd.eContents();
		var MessageNum = 0;
		for (EObject ob : allContents) {
    		if (ob instanceof Message) {
    			val m = ob as Message;
    			val sendEnd = SequenceDiagramFactory.eINSTANCE.createMessageEnd();
    			val receiveEnd = SequenceDiagramFactory.eINSTANCE.createMessageEnd();
    			// 生成相应的AbstractMessage
    			if (ob.arrow.SYNC !== null) {
    				val callMessage = SequenceDiagramFactory.eINSTANCE.createCallMessage();
    				callMessage.description = m.description
    				callMessage.sendingEnd = sendEnd
    				callMessage.receivingEnd = receiveEnd
    				callMessage.name = 'callMsg' + MessageNum
    				sendEnd.message = callMessage 
    				receiveEnd.message = callMessage
    				sd.messages.add(callMessage)
    			} else if (ob.arrow.RETURN !== null) {
    				val returnMessage = SequenceDiagramFactory.eINSTANCE.createReturnMessage();
					returnMessage.description = m.description
					returnMessage.sendingEnd = sendEnd
    				returnMessage.receivingEnd = receiveEnd
    				returnMessage.name = 'returnMsg' + MessageNum
    				sendEnd.message = returnMessage
    				receiveEnd.message = returnMessage
    				sd.messages.add(returnMessage)
    			}
    			
    			sendEnd.setContext(m.getSender());
    			sendEnd.setName("Message" + MessageNum + "SenderEnd");
    			sd.ends.add(sendEnd);
    			ends.add(sendEnd)
    			
    			// 这里暂时不处理Execution和Participant混合End的情况
    			receiveEnd.setContext(m.getReceiver());
    			receiveEnd.setName("Message" + MessageNum + "ReceiveEnd");
    			MessageNum++;
    			sd.ends.add(receiveEnd)
    			ends.add(receiveEnd);
    		} else if (ob instanceof Activation) {
    			val activation = ob as Activation;
    			val startEnd = SequenceDiagramFactory.eINSTANCE.createExecutionStart();
    			startEnd.setContext(activation.getContext());
    			sd.ends.add(startEnd);
    			ends.add(startEnd)
    		} else if (ob instanceof Deactivation) {
    			val deactivation = ob as Deactivation;
    			val finishEnd = SequenceDiagramFactory.eINSTANCE.createExecutionEnd();
    			finishEnd.setContext(deactivation.getContext());
    			sd.ends.add(finishEnd);
    			ends.add(finishEnd)
    		}
    	}
	}
	
	def void generateExecutions(SequenceDiagram sd) {
		val map = new HashMap<MultiContext, Deque<MixEnd>>();
		// 对于嵌套Execution，key所在的Execution为value所在Execution的Context
		val ssmap = new HashMap<MixEnd, ArrayList<ExecutionStart>>();
		val semap = new HashMap<MixEnd, ArrayList<ExecutionEnd>>();
		var executionNum = 0;
    	for (EObject tmp : ends) {
    		val end = tmp as MixEnd;
    		if (end instanceof ExecutionStart) {
    			if(map.containsKey(end.getContext())) {
    				val stack = map.get(end.getContext());
    				stack.push(end);
    			} else {
    				val stack = new ArrayDeque<MixEnd>();
    				stack.push(end);
    				map.put(end.getContext(), stack);
    			}
    		} else if (end instanceof ExecutionEnd) {
    			if (!map.containsKey(end.getContext()) || map.get(end.getContext()).isEmpty()) {
    				System.out.println("No ExecutionStart for ExecutionEnd");
    			} else {
    				val stack = map.get(end.getContext());
	    			// 跟栈顶的Start完成匹配
	    			// 1. 栈顶Start出栈
	    			val eStart = stack.pop() as ExecutionStart;
	    			val eEnd = end as ExecutionEnd;
	    			// 2. 创建一个Execution，并设置其相关属性
	    			val execution = SequenceDiagramFactory.eINSTANCE.createExecution();
	    			execution.setStart(eStart);
	    			execution.setEnd(eEnd);
	    			println(end + end.getContext().toString())
	    			var participant = end.getContext() as Participant
	    			execution.setOwner(participant);
	    			execution.setName('execution' + executionNum);
	    			sd.executions.add(execution)
	    			if (ssmap.containsKey(eStart) && !ssmap.get(eStart).isEmpty()) {
	    				for (ExecutionStart startTBD : ssmap.get(eStart)) {
	    					startTBD.setContext(execution)
	    				}
	    			}
	    			if (ssmap.containsKey(eStart) && !semap.get(eStart).isEmpty()) {
	    				for (ExecutionEnd endTBD : semap.get(eStart)) {
	    					endTBD.setContext(execution)
	    				}
	    			}

	    			// 3. 设置Start和End的相关属性
	    			eStart.setExecution(execution);
	    			eStart.setName('executionStart' + executionNum);
	    			eEnd.setExecution(execution);
	    			eEnd.setName('executionEnd' + executionNum);
	    			// 4. 如果当前stack中还存在Start，说明当前Execution是嵌套Execution, End的Context需要稍后处理
	    			if (!stack.isEmpty()) {
	    				if (ssmap.containsKey(stack.peek())) {
	    					ssmap.get(stack.peek()).add(eStart)
	    					semap.get(stack.peek()).add(eEnd)
	    				} else {
	    					val startList = new ArrayList<ExecutionStart>()
	    					startList.add(eStart)
	    					ssmap.put(stack.peek(), startList)
	    					val endList = new ArrayList<ExecutionEnd>()
	    					endList.add(eEnd)
	    					semap.put(stack.peek(), endList)
	    				}
	    			} else {
	    				eStart.setContext(participant);
	    				eEnd.setContext(participant);
	    			}
	    			executionNum++				
    			}
    		}
    	}	
	}
	

	
}