/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.sd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SequenceDiagramStandaloneSetup extends SequenceDiagramStandaloneSetupGenerated {

	public static void doSetup() {
		new SequenceDiagramStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
