/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.sd;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SequenceDiagramRuntimeModule extends AbstractSequenceDiagramRuntimeModule {
}
