/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ClassDiagramAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/rm2pt/rapidood/cd/parser/antlr/internal/InternalClassDiagram.tokens");
	}
}
