/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.parser.antlr;

import com.google.inject.Inject;
import com.rm2pt.rapidood.cd.parser.antlr.internal.InternalClassDiagramParser;
import com.rm2pt.rapidood.cd.services.ClassDiagramGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ClassDiagramParser extends AbstractAntlrParser {

	@Inject
	private ClassDiagramGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalClassDiagramParser createParser(XtextTokenStream stream) {
		return new InternalClassDiagramParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ClassDiagram";
	}

	public ClassDiagramGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ClassDiagramGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
