/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.sd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SequenceDiagramUiModule extends AbstractSequenceDiagramUiModule {

	public SequenceDiagramUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
