/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ClassDiagramStandaloneSetup extends ClassDiagramStandaloneSetupGenerated {

	public static void doSetup() {
		new ClassDiagramStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
