/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd;

import org.eclipse.xtext.formatting2.IFormatter2;
import org.eclipse.xtext.scoping.IScopeProvider;

import com.rm2pt.rapidood.cd.scoping.ClassDiagramScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ClassDiagramRuntimeModule extends AbstractClassDiagramRuntimeModule {
    @Override
    public Class<? extends IScopeProvider> bindIScopeProvider() {
		return ClassDiagramScopeProvider.class;
	}
    

}
