/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.classDiagram.impl;

import com.rm2pt.rapidood.cd.classDiagram.AbstractClass;
import com.rm2pt.rapidood.cd.classDiagram.AbstractElement;
import com.rm2pt.rapidood.cd.classDiagram.Attribute;
import com.rm2pt.rapidood.cd.classDiagram.ClassDiagram;
import com.rm2pt.rapidood.cd.classDiagram.ClassDiagramFactory;
import com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage;
import com.rm2pt.rapidood.cd.classDiagram.EnumItem;
import com.rm2pt.rapidood.cd.classDiagram.Interface;
import com.rm2pt.rapidood.cd.classDiagram.Operation;
import com.rm2pt.rapidood.cd.classDiagram.PackageDeclaration;
import com.rm2pt.rapidood.cd.classDiagram.Parameter;
import com.rm2pt.rapidood.cd.classDiagram.PrimitiveType;
import com.rm2pt.rapidood.cd.classDiagram.ReferType;
import com.rm2pt.rapidood.cd.classDiagram.Relationship;
import com.rm2pt.rapidood.cd.classDiagram.Type;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ClassDiagramFactoryImpl extends EFactoryImpl implements ClassDiagramFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ClassDiagramFactory init()
  {
    try
    {
      ClassDiagramFactory theClassDiagramFactory = (ClassDiagramFactory)EPackage.Registry.INSTANCE.getEFactory(ClassDiagramPackage.eNS_URI);
      if (theClassDiagramFactory != null)
      {
        return theClassDiagramFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ClassDiagramFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassDiagramFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ClassDiagramPackage.CLASS_DIAGRAM: return createClassDiagram();
      case ClassDiagramPackage.ABSTRACT_ELEMENT: return createAbstractElement();
      case ClassDiagramPackage.PACKAGE_DECLARATION: return createPackageDeclaration();
      case ClassDiagramPackage.CLASS: return createClass();
      case ClassDiagramPackage.INTERFACE: return createInterface();
      case ClassDiagramPackage.ABSTRACT_CLASS: return createAbstractClass();
      case ClassDiagramPackage.ATTRIBUTE: return createAttribute();
      case ClassDiagramPackage.OPERATION: return createOperation();
      case ClassDiagramPackage.PARAMETER: return createParameter();
      case ClassDiagramPackage.RELATIONSHIP: return createRelationship();
      case ClassDiagramPackage.TYPE: return createType();
      case ClassDiagramPackage.PRIMITIVE_TYPE: return createPrimitiveType();
      case ClassDiagramPackage.REFER_TYPE: return createReferType();
      case ClassDiagramPackage.ENUM_ITEM: return createEnumItem();
      case ClassDiagramPackage.ENUM: return createEnum();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClassDiagram createClassDiagram()
  {
    ClassDiagramImpl classDiagram = new ClassDiagramImpl();
    return classDiagram;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbstractElement createAbstractElement()
  {
    AbstractElementImpl abstractElement = new AbstractElementImpl();
    return abstractElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PackageDeclaration createPackageDeclaration()
  {
    PackageDeclarationImpl packageDeclaration = new PackageDeclarationImpl();
    return packageDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public com.rm2pt.rapidood.cd.classDiagram.Class createClass()
  {
    ClassImpl class_ = new ClassImpl();
    return class_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interface createInterface()
  {
    InterfaceImpl interface_ = new InterfaceImpl();
    return interface_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbstractClass createAbstractClass()
  {
    AbstractClassImpl abstractClass = new AbstractClassImpl();
    return abstractClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute createAttribute()
  {
    AttributeImpl attribute = new AttributeImpl();
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operation createOperation()
  {
    OperationImpl operation = new OperationImpl();
    return operation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Parameter createParameter()
  {
    ParameterImpl parameter = new ParameterImpl();
    return parameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Relationship createRelationship()
  {
    RelationshipImpl relationship = new RelationshipImpl();
    return relationship;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Type createType()
  {
    TypeImpl type = new TypeImpl();
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrimitiveType createPrimitiveType()
  {
    PrimitiveTypeImpl primitiveType = new PrimitiveTypeImpl();
    return primitiveType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReferType createReferType()
  {
    ReferTypeImpl referType = new ReferTypeImpl();
    return referType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EnumItem createEnumItem()
  {
    EnumItemImpl enumItem = new EnumItemImpl();
    return enumItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public com.rm2pt.rapidood.cd.classDiagram.Enum createEnum()
  {
    EnumImpl enum_ = new EnumImpl();
    return enum_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClassDiagramPackage getClassDiagramPackage()
  {
    return (ClassDiagramPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ClassDiagramPackage getPackage()
  {
    return ClassDiagramPackage.eINSTANCE;
  }

} //ClassDiagramFactoryImpl
