/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.classDiagram.impl;

import com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage;
import com.rm2pt.rapidood.cd.classDiagram.ReferType;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Refer Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ReferTypeImpl extends TypeImpl implements ReferType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReferTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ClassDiagramPackage.Literals.REFER_TYPE;
  }

} //ReferTypeImpl
