/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.classDiagram.impl;

import com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage;
import com.rm2pt.rapidood.cd.classDiagram.Relationship;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relationship</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl#getLeft <em>Left</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl#getLeftCardinality <em>Left Cardinality</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl#getLeftDecorator <em>Left Decorator</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl#getLine <em>Line</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl#getRightDecorator <em>Right Decorator</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl#getRightCardinality <em>Right Cardinality</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl#getRight <em>Right</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl#getLabel <em>Label</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RelationshipImpl extends AbstractElementImpl implements Relationship
{
  /**
   * The cached value of the '{@link #getLeft() <em>Left</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeft()
   * @generated
   * @ordered
   */
  protected com.rm2pt.rapidood.cd.classDiagram.Class left;

  /**
   * The default value of the '{@link #getLeftCardinality() <em>Left Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeftCardinality()
   * @generated
   * @ordered
   */
  protected static final String LEFT_CARDINALITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLeftCardinality() <em>Left Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeftCardinality()
   * @generated
   * @ordered
   */
  protected String leftCardinality = LEFT_CARDINALITY_EDEFAULT;

  /**
   * The default value of the '{@link #getLeftDecorator() <em>Left Decorator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeftDecorator()
   * @generated
   * @ordered
   */
  protected static final String LEFT_DECORATOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLeftDecorator() <em>Left Decorator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeftDecorator()
   * @generated
   * @ordered
   */
  protected String leftDecorator = LEFT_DECORATOR_EDEFAULT;

  /**
   * The default value of the '{@link #getLine() <em>Line</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLine()
   * @generated
   * @ordered
   */
  protected static final String LINE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLine() <em>Line</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLine()
   * @generated
   * @ordered
   */
  protected String line = LINE_EDEFAULT;

  /**
   * The default value of the '{@link #getRightDecorator() <em>Right Decorator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRightDecorator()
   * @generated
   * @ordered
   */
  protected static final String RIGHT_DECORATOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRightDecorator() <em>Right Decorator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRightDecorator()
   * @generated
   * @ordered
   */
  protected String rightDecorator = RIGHT_DECORATOR_EDEFAULT;

  /**
   * The default value of the '{@link #getRightCardinality() <em>Right Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRightCardinality()
   * @generated
   * @ordered
   */
  protected static final String RIGHT_CARDINALITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRightCardinality() <em>Right Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRightCardinality()
   * @generated
   * @ordered
   */
  protected String rightCardinality = RIGHT_CARDINALITY_EDEFAULT;

  /**
   * The cached value of the '{@link #getRight() <em>Right</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRight()
   * @generated
   * @ordered
   */
  protected com.rm2pt.rapidood.cd.classDiagram.Class right;

  /**
   * The default value of the '{@link #getLabel() <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabel()
   * @generated
   * @ordered
   */
  protected static final String LABEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLabel() <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabel()
   * @generated
   * @ordered
   */
  protected String label = LABEL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelationshipImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ClassDiagramPackage.Literals.RELATIONSHIP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public com.rm2pt.rapidood.cd.classDiagram.Class getLeft()
  {
    if (left != null && left.eIsProxy())
    {
      InternalEObject oldLeft = (InternalEObject)left;
      left = (com.rm2pt.rapidood.cd.classDiagram.Class)eResolveProxy(oldLeft);
      if (left != oldLeft)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ClassDiagramPackage.RELATIONSHIP__LEFT, oldLeft, left));
      }
    }
    return left;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public com.rm2pt.rapidood.cd.classDiagram.Class basicGetLeft()
  {
    return left;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLeft(com.rm2pt.rapidood.cd.classDiagram.Class newLeft)
  {
    com.rm2pt.rapidood.cd.classDiagram.Class oldLeft = left;
    left = newLeft;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ClassDiagramPackage.RELATIONSHIP__LEFT, oldLeft, left));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLeftCardinality()
  {
    return leftCardinality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLeftCardinality(String newLeftCardinality)
  {
    String oldLeftCardinality = leftCardinality;
    leftCardinality = newLeftCardinality;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ClassDiagramPackage.RELATIONSHIP__LEFT_CARDINALITY, oldLeftCardinality, leftCardinality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLeftDecorator()
  {
    return leftDecorator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLeftDecorator(String newLeftDecorator)
  {
    String oldLeftDecorator = leftDecorator;
    leftDecorator = newLeftDecorator;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ClassDiagramPackage.RELATIONSHIP__LEFT_DECORATOR, oldLeftDecorator, leftDecorator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLine()
  {
    return line;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLine(String newLine)
  {
    String oldLine = line;
    line = newLine;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ClassDiagramPackage.RELATIONSHIP__LINE, oldLine, line));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRightDecorator()
  {
    return rightDecorator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRightDecorator(String newRightDecorator)
  {
    String oldRightDecorator = rightDecorator;
    rightDecorator = newRightDecorator;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ClassDiagramPackage.RELATIONSHIP__RIGHT_DECORATOR, oldRightDecorator, rightDecorator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRightCardinality()
  {
    return rightCardinality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRightCardinality(String newRightCardinality)
  {
    String oldRightCardinality = rightCardinality;
    rightCardinality = newRightCardinality;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ClassDiagramPackage.RELATIONSHIP__RIGHT_CARDINALITY, oldRightCardinality, rightCardinality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public com.rm2pt.rapidood.cd.classDiagram.Class getRight()
  {
    if (right != null && right.eIsProxy())
    {
      InternalEObject oldRight = (InternalEObject)right;
      right = (com.rm2pt.rapidood.cd.classDiagram.Class)eResolveProxy(oldRight);
      if (right != oldRight)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ClassDiagramPackage.RELATIONSHIP__RIGHT, oldRight, right));
      }
    }
    return right;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public com.rm2pt.rapidood.cd.classDiagram.Class basicGetRight()
  {
    return right;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRight(com.rm2pt.rapidood.cd.classDiagram.Class newRight)
  {
    com.rm2pt.rapidood.cd.classDiagram.Class oldRight = right;
    right = newRight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ClassDiagramPackage.RELATIONSHIP__RIGHT, oldRight, right));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLabel()
  {
    return label;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLabel(String newLabel)
  {
    String oldLabel = label;
    label = newLabel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ClassDiagramPackage.RELATIONSHIP__LABEL, oldLabel, label));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ClassDiagramPackage.RELATIONSHIP__LEFT:
        if (resolve) return getLeft();
        return basicGetLeft();
      case ClassDiagramPackage.RELATIONSHIP__LEFT_CARDINALITY:
        return getLeftCardinality();
      case ClassDiagramPackage.RELATIONSHIP__LEFT_DECORATOR:
        return getLeftDecorator();
      case ClassDiagramPackage.RELATIONSHIP__LINE:
        return getLine();
      case ClassDiagramPackage.RELATIONSHIP__RIGHT_DECORATOR:
        return getRightDecorator();
      case ClassDiagramPackage.RELATIONSHIP__RIGHT_CARDINALITY:
        return getRightCardinality();
      case ClassDiagramPackage.RELATIONSHIP__RIGHT:
        if (resolve) return getRight();
        return basicGetRight();
      case ClassDiagramPackage.RELATIONSHIP__LABEL:
        return getLabel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ClassDiagramPackage.RELATIONSHIP__LEFT:
        setLeft((com.rm2pt.rapidood.cd.classDiagram.Class)newValue);
        return;
      case ClassDiagramPackage.RELATIONSHIP__LEFT_CARDINALITY:
        setLeftCardinality((String)newValue);
        return;
      case ClassDiagramPackage.RELATIONSHIP__LEFT_DECORATOR:
        setLeftDecorator((String)newValue);
        return;
      case ClassDiagramPackage.RELATIONSHIP__LINE:
        setLine((String)newValue);
        return;
      case ClassDiagramPackage.RELATIONSHIP__RIGHT_DECORATOR:
        setRightDecorator((String)newValue);
        return;
      case ClassDiagramPackage.RELATIONSHIP__RIGHT_CARDINALITY:
        setRightCardinality((String)newValue);
        return;
      case ClassDiagramPackage.RELATIONSHIP__RIGHT:
        setRight((com.rm2pt.rapidood.cd.classDiagram.Class)newValue);
        return;
      case ClassDiagramPackage.RELATIONSHIP__LABEL:
        setLabel((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ClassDiagramPackage.RELATIONSHIP__LEFT:
        setLeft((com.rm2pt.rapidood.cd.classDiagram.Class)null);
        return;
      case ClassDiagramPackage.RELATIONSHIP__LEFT_CARDINALITY:
        setLeftCardinality(LEFT_CARDINALITY_EDEFAULT);
        return;
      case ClassDiagramPackage.RELATIONSHIP__LEFT_DECORATOR:
        setLeftDecorator(LEFT_DECORATOR_EDEFAULT);
        return;
      case ClassDiagramPackage.RELATIONSHIP__LINE:
        setLine(LINE_EDEFAULT);
        return;
      case ClassDiagramPackage.RELATIONSHIP__RIGHT_DECORATOR:
        setRightDecorator(RIGHT_DECORATOR_EDEFAULT);
        return;
      case ClassDiagramPackage.RELATIONSHIP__RIGHT_CARDINALITY:
        setRightCardinality(RIGHT_CARDINALITY_EDEFAULT);
        return;
      case ClassDiagramPackage.RELATIONSHIP__RIGHT:
        setRight((com.rm2pt.rapidood.cd.classDiagram.Class)null);
        return;
      case ClassDiagramPackage.RELATIONSHIP__LABEL:
        setLabel(LABEL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ClassDiagramPackage.RELATIONSHIP__LEFT:
        return left != null;
      case ClassDiagramPackage.RELATIONSHIP__LEFT_CARDINALITY:
        return LEFT_CARDINALITY_EDEFAULT == null ? leftCardinality != null : !LEFT_CARDINALITY_EDEFAULT.equals(leftCardinality);
      case ClassDiagramPackage.RELATIONSHIP__LEFT_DECORATOR:
        return LEFT_DECORATOR_EDEFAULT == null ? leftDecorator != null : !LEFT_DECORATOR_EDEFAULT.equals(leftDecorator);
      case ClassDiagramPackage.RELATIONSHIP__LINE:
        return LINE_EDEFAULT == null ? line != null : !LINE_EDEFAULT.equals(line);
      case ClassDiagramPackage.RELATIONSHIP__RIGHT_DECORATOR:
        return RIGHT_DECORATOR_EDEFAULT == null ? rightDecorator != null : !RIGHT_DECORATOR_EDEFAULT.equals(rightDecorator);
      case ClassDiagramPackage.RELATIONSHIP__RIGHT_CARDINALITY:
        return RIGHT_CARDINALITY_EDEFAULT == null ? rightCardinality != null : !RIGHT_CARDINALITY_EDEFAULT.equals(rightCardinality);
      case ClassDiagramPackage.RELATIONSHIP__RIGHT:
        return right != null;
      case ClassDiagramPackage.RELATIONSHIP__LABEL:
        return LABEL_EDEFAULT == null ? label != null : !LABEL_EDEFAULT.equals(label);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (leftCardinality: ");
    result.append(leftCardinality);
    result.append(", leftDecorator: ");
    result.append(leftDecorator);
    result.append(", line: ");
    result.append(line);
    result.append(", rightDecorator: ");
    result.append(rightDecorator);
    result.append(", rightCardinality: ");
    result.append(rightCardinality);
    result.append(", label: ");
    result.append(label);
    result.append(')');
    return result.toString();
  }

} //RelationshipImpl
