/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.sd.ide;


/**
 * Use this class to register ide components.
 */
public class SequenceDiagramIdeModule extends AbstractSequenceDiagramIdeModule {
}
