/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.sd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.rm2pt.rapidood.sd.SequenceDiagramRuntimeModule;
import com.rm2pt.rapidood.sd.SequenceDiagramStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SequenceDiagramIdeSetup extends SequenceDiagramStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SequenceDiagramRuntimeModule(), new SequenceDiagramIdeModule()));
	}
	
}
