/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class ClassDiagramFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private /* ClassDiagramGrammarAccess */Object _classDiagramGrammarAccess;
  
  protected void _format(final /* ClassDiagram */Object classDiagram, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method setNewLines(int) is undefined"
      + "\nThe method setNewLines(int) is undefined"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nelements cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final /* PackageDeclaration */Object packageDeclaration, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method setNewLines(int) is undefined"
      + "\nThe method setNewLines(int) is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nkeyword cannot be resolved"
      + "\nprepend cannot be resolved"
      + "\nappend cannot be resolved"
      + "\nelements cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final Class clz, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field attributes is undefined for the type Class"
      + "\nThe method or field operations is undefined for the type Class"
      + "\nType mismatch: cannot convert from Class to EObject"
      + "\nType mismatch: cannot convert from Class to EObject"
      + "\nformat cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final /* Attribute */Object attr, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field newLine is undefined"
      + "\nappend cannot be resolved");
  }
  
  protected void _format(final /* Operation */Object op, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field newLine is undefined"
      + "\nappend cannot be resolved");
  }
  
  protected void _format(final Enum enu, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field values is undefined for the type Enum"
      + "\nType mismatch: cannot convert from Enum to EObject"
      + "\nType mismatch: cannot convert from Enum to EObject"
      + "\nType mismatch: cannot convert from Enum to ISemanticRegion"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final /* EnumItem */Object enumItem, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field newLine is undefined"
      + "\nappend cannot be resolved");
  }
  
  protected void _format(final /* Relationship */Object relation, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field RELATIONSHIP__LINE is undefined"
      + "\nThe method or field noSpace is undefined"
      + "\nThe method or field RELATIONSHIP__RIGHT is undefined"
      + "\nThe method or field RELATIONSHIP__LABEL is undefined"
      + "\nThe method or field newLine is undefined"
      + "\nregionFor cannot be resolved"
      + "\nfeature cannot be resolved"
      + "\nsurround cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nfeature cannot be resolved"
      + "\nregionFor cannot be resolved"
      + "\nfeature cannot be resolved"
      + "\n?: cannot be resolved"
      + "\nappend cannot be resolved");
  }
  
  public void format(final Object clz, final IFormattableDocument document) {
    if (clz instanceof XtextResource) {
      _format((XtextResource)clz, document);
      return;
    } else if (clz instanceof Class) {
      _format((Class)clz, document);
      return;
    } else if (clz instanceof Enum) {
      _format((Enum)clz, document);
      return;
    } else if (clz instanceof EObject) {
      _format((EObject)clz, document);
      return;
    } else if (clz == null) {
      _format((Void)null, document);
      return;
    } else if (clz != null) {
      _format(clz, document);
      return;
    } else if (clz != null) {
      _format(clz, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(clz, document).toString());
    }
  }
}
