/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ClassDiagramProposalProvider extends AbstractClassDiagramProposalProvider {
}
