/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.sd.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)/* 
@InjectWith(/* name is null */) */
@SuppressWarnings("all")
public class SequenceDiagramParsingTest {
  @Inject
  private /* ParseHelper<SequenceDiagram> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SequenceDiagramParsingTest.parseHelper refers to the missing type SequenceDiagram"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
