/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ClassDiagramGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ClassDiagramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.ClassDiagram");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClassDiagramAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStartumlKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementsAbstractElementParserRuleCall_2_0 = (RuleCall)cElementsAssignment_2.eContents().get(0);
		private final Keyword cEndumlKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ClassDiagram:
		//    {ClassDiagram}
		//    '@startuml'
		//    (elements += AbstractElement)*
		//    '@enduml'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{ClassDiagram}
		//'@startuml'
		//(elements += AbstractElement)*
		//'@enduml'
		public Group getGroup() { return cGroup; }
		
		//{ClassDiagram}
		public Action getClassDiagramAction_0() { return cClassDiagramAction_0; }
		
		//'@startuml'
		public Keyword getStartumlKeyword_1() { return cStartumlKeyword_1; }
		
		//(elements += AbstractElement)*
		public Assignment getElementsAssignment_2() { return cElementsAssignment_2; }
		
		//AbstractElement
		public RuleCall getElementsAbstractElementParserRuleCall_2_0() { return cElementsAbstractElementParserRuleCall_2_0; }
		
		//'@enduml'
		public Keyword getEndumlKeyword_3() { return cEndumlKeyword_3; }
	}
	public class AbstractElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.AbstractElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPackageDeclarationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cClassParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInterfaceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cAbstractClassParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRelationshipParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cEnumParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//AbstractElement:
		//    PackageDeclaration | Class | Interface | AbstractClass | Relationship | Enum
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//PackageDeclaration | Class | Interface | AbstractClass | Relationship | Enum
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PackageDeclaration
		public RuleCall getPackageDeclarationParserRuleCall_0() { return cPackageDeclarationParserRuleCall_0; }
		
		//Class
		public RuleCall getClassParserRuleCall_1() { return cClassParserRuleCall_1; }
		
		//Interface
		public RuleCall getInterfaceParserRuleCall_2() { return cInterfaceParserRuleCall_2; }
		
		//AbstractClass
		public RuleCall getAbstractClassParserRuleCall_3() { return cAbstractClassParserRuleCall_3; }
		
		//Relationship
		public RuleCall getRelationshipParserRuleCall_4() { return cRelationshipParserRuleCall_4; }
		
		//Enum
		public RuleCall getEnumParserRuleCall_5() { return cEnumParserRuleCall_5; }
	}
	public class PackageDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.PackageDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPackageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameFQNParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cElementsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cElementsAbstractElementParserRuleCall_3_0 = (RuleCall)cElementsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//PackageDeclaration:
		//    'package' name=FQN '{'
		//            (elements += AbstractElement)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'package' name=FQN '{'
		//        (elements += AbstractElement)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'package'
		public Keyword getPackageKeyword_0() { return cPackageKeyword_0; }
		
		//name=FQN
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//FQN
		public RuleCall getNameFQNParserRuleCall_1_0() { return cNameFQNParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(elements += AbstractElement)*
		public Assignment getElementsAssignment_3() { return cElementsAssignment_3; }
		
		//AbstractElement
		public RuleCall getElementsAbstractElementParserRuleCall_3_0() { return cElementsAbstractElementParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class FQNElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.FQN");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//FQN:
		//    ID (=>'.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID (=>'.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//(=>'.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//=>'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class ClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Class");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClassKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSimpleNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAttributesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAttributesAttributeParserRuleCall_3_0 = (RuleCall)cAttributesAssignment_3.eContents().get(0);
		private final Assignment cOperationsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOperationsOperationParserRuleCall_4_0 = (RuleCall)cOperationsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Class:
		//    'class' name=SimpleName '{'
		//            (attributes += Attribute)*
		//            (operations += Operation)*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'class' name=SimpleName '{'
		//        (attributes += Attribute)*
		//        (operations += Operation)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'class'
		public Keyword getClassKeyword_0() { return cClassKeyword_0; }
		
		//name=SimpleName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//SimpleName
		public RuleCall getNameSimpleNameParserRuleCall_1_0() { return cNameSimpleNameParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(attributes += Attribute)*
		public Assignment getAttributesAssignment_3() { return cAttributesAssignment_3; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_3_0() { return cAttributesAttributeParserRuleCall_3_0; }
		
		//(operations += Operation)*
		public Assignment getOperationsAssignment_4() { return cOperationsAssignment_4; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_4_0() { return cOperationsOperationParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class InterfaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Interface");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInterfaceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSimpleNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAttributesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAttributesAttributeParserRuleCall_3_0 = (RuleCall)cAttributesAssignment_3.eContents().get(0);
		private final Assignment cOperationsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOperationsOperationParserRuleCall_4_0 = (RuleCall)cOperationsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Interface:
		//    'interface' name=SimpleName '{'
		//            (attributes += Attribute)*
		//            (operations += Operation)*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'interface' name=SimpleName '{'
		//        (attributes += Attribute)*
		//        (operations += Operation)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'interface'
		public Keyword getInterfaceKeyword_0() { return cInterfaceKeyword_0; }
		
		//name=SimpleName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//SimpleName
		public RuleCall getNameSimpleNameParserRuleCall_1_0() { return cNameSimpleNameParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(attributes += Attribute)*
		public Assignment getAttributesAssignment_3() { return cAttributesAssignment_3; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_3_0() { return cAttributesAttributeParserRuleCall_3_0; }
		
		//(operations += Operation)*
		public Assignment getOperationsAssignment_4() { return cOperationsAssignment_4; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_4_0() { return cOperationsOperationParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class AbstractClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.AbstractClass");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAbstractKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSimpleNameParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAttributesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAttributesAttributeParserRuleCall_4_0 = (RuleCall)cAttributesAssignment_4.eContents().get(0);
		private final Assignment cOperationsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOperationsOperationParserRuleCall_5_0 = (RuleCall)cOperationsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//AbstractClass:
		//    ('abstract') ('class')? name=SimpleName '{'
		//            (attributes += Attribute)*
		//            (operations += Operation)*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//('abstract') ('class')? name=SimpleName '{'
		//        (attributes += Attribute)*
		//        (operations += Operation)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//('abstract')
		public Keyword getAbstractKeyword_0() { return cAbstractKeyword_0; }
		
		//('class')?
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }
		
		//name=SimpleName
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//SimpleName
		public RuleCall getNameSimpleNameParserRuleCall_2_0() { return cNameSimpleNameParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(attributes += Attribute)*
		public Assignment getAttributesAssignment_4() { return cAttributesAssignment_4; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_4_0() { return cAttributesAttributeParserRuleCall_4_0; }
		
		//(operations += Operation)*
		public Assignment getOperationsAssignment_5() { return cOperationsAssignment_5; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_5_0() { return cOperationsOperationParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SimpleNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.SimpleName");
		private final RuleCall cIDTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//SimpleName hidden():
		//    ID;
		@Override public ParserRule getRule() { return rule; }
		
		//ID
		public RuleCall getIDTerminalRuleCall() { return cIDTerminalRuleCall; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVisibilityAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVisibilityVisibilityParserRuleCall_0_0 = (RuleCall)cVisibilityAssignment_0.eContents().get(0);
		private final Assignment cIsStaticAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIsStaticStaticKeyword_1_0 = (Keyword)cIsStaticAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSimpleNameParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeTypeParserRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		
		//Attribute:
		//    visibility=Visibility? (isStatic?='{static}')? name=SimpleName ':' type=Type;
		@Override public ParserRule getRule() { return rule; }
		
		//visibility=Visibility? (isStatic?='{static}')? name=SimpleName ':' type=Type
		public Group getGroup() { return cGroup; }
		
		//visibility=Visibility?
		public Assignment getVisibilityAssignment_0() { return cVisibilityAssignment_0; }
		
		//Visibility
		public RuleCall getVisibilityVisibilityParserRuleCall_0_0() { return cVisibilityVisibilityParserRuleCall_0_0; }
		
		//(isStatic?='{static}')?
		public Assignment getIsStaticAssignment_1() { return cIsStaticAssignment_1; }
		
		//'{static}'
		public Keyword getIsStaticStaticKeyword_1_0() { return cIsStaticStaticKeyword_1_0; }
		
		//name=SimpleName
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//SimpleName
		public RuleCall getNameSimpleNameParserRuleCall_2_0() { return cNameSimpleNameParserRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//type=Type
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_4_0() { return cTypeTypeParserRuleCall_4_0; }
	}
	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Operation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVisibilityAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVisibilityVisibilityParserRuleCall_0_0 = (RuleCall)cVisibilityAssignment_0.eContents().get(0);
		private final Assignment cIsAbstractAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIsAbstractAbstractKeyword_1_0 = (Keyword)cIsAbstractAssignment_1.eContents().get(0);
		private final Assignment cIsStaticAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cIsStaticStaticKeyword_2_0 = (Keyword)cIsStaticAssignment_2.eContents().get(0);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameSimpleNameParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cParamsAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cParamsParameterParserRuleCall_5_0_0 = (RuleCall)cParamsAssignment_5_0.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Keyword cCommaKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cParamsAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cParamsParameterParserRuleCall_5_1_1_0 = (RuleCall)cParamsAssignment_5_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cReturnTypeAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cReturnTypeTypeParserRuleCall_8_0 = (RuleCall)cReturnTypeAssignment_8.eContents().get(0);
		
		//Operation:
		//    visibility=Visibility? (isAbstract?='{abstract}')? (isStatic?='{static}')?
		//    name=SimpleName '(' (params+=Parameter (',' params+=Parameter)*)? ')' ':' returnType=Type;
		@Override public ParserRule getRule() { return rule; }
		
		//visibility=Visibility? (isAbstract?='{abstract}')? (isStatic?='{static}')?
		//name=SimpleName '(' (params+=Parameter (',' params+=Parameter)*)? ')' ':' returnType=Type
		public Group getGroup() { return cGroup; }
		
		//visibility=Visibility?
		public Assignment getVisibilityAssignment_0() { return cVisibilityAssignment_0; }
		
		//Visibility
		public RuleCall getVisibilityVisibilityParserRuleCall_0_0() { return cVisibilityVisibilityParserRuleCall_0_0; }
		
		//(isAbstract?='{abstract}')?
		public Assignment getIsAbstractAssignment_1() { return cIsAbstractAssignment_1; }
		
		//'{abstract}'
		public Keyword getIsAbstractAbstractKeyword_1_0() { return cIsAbstractAbstractKeyword_1_0; }
		
		//(isStatic?='{static}')?
		public Assignment getIsStaticAssignment_2() { return cIsStaticAssignment_2; }
		
		//'{static}'
		public Keyword getIsStaticStaticKeyword_2_0() { return cIsStaticStaticKeyword_2_0; }
		
		//name=SimpleName
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//SimpleName
		public RuleCall getNameSimpleNameParserRuleCall_3_0() { return cNameSimpleNameParserRuleCall_3_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//(params+=Parameter (',' params+=Parameter)*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//params+=Parameter
		public Assignment getParamsAssignment_5_0() { return cParamsAssignment_5_0; }
		
		//Parameter
		public RuleCall getParamsParameterParserRuleCall_5_0_0() { return cParamsParameterParserRuleCall_5_0_0; }
		
		//(',' params+=Parameter)*
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//','
		public Keyword getCommaKeyword_5_1_0() { return cCommaKeyword_5_1_0; }
		
		//params+=Parameter
		public Assignment getParamsAssignment_5_1_1() { return cParamsAssignment_5_1_1; }
		
		//Parameter
		public RuleCall getParamsParameterParserRuleCall_5_1_1_0() { return cParamsParameterParserRuleCall_5_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//':'
		public Keyword getColonKeyword_7() { return cColonKeyword_7; }
		
		//returnType=Type
		public Assignment getReturnTypeAssignment_8() { return cReturnTypeAssignment_8; }
		
		//Type
		public RuleCall getReturnTypeTypeParserRuleCall_8_0() { return cReturnTypeTypeParserRuleCall_8_0; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeTypeParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSimpleNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Parameter:
		//    type=Type name=SimpleName;
		@Override public ParserRule getRule() { return rule; }
		
		//type=Type name=SimpleName
		public Group getGroup() { return cGroup; }
		
		//type=Type
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_0_0() { return cTypeTypeParserRuleCall_0_0; }
		
		//name=SimpleName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//SimpleName
		public RuleCall getNameSimpleNameParserRuleCall_1_0() { return cNameSimpleNameParserRuleCall_1_0; }
	}
	public class VisibilityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Visibility");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cNumberSignKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cTildeKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//Visibility:
		//    '+' | '-' | '#' | '~';
		@Override public ParserRule getRule() { return rule; }
		
		//'+' | '-' | '#' | '~'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'+'
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//'#'
		public Keyword getNumberSignKeyword_2() { return cNumberSignKeyword_2; }
		
		//'~'
		public Keyword getTildeKeyword_3() { return cTildeKeyword_3; }
	}
	public class RelationshipElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Relationship");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRelationshipAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cLeftAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cLeftClassCrossReference_1_0 = (CrossReference)cLeftAssignment_1.eContents().get(0);
		private final RuleCall cLeftClassFQNParserRuleCall_1_0_1 = (RuleCall)cLeftClassCrossReference_1_0.eContents().get(1);
		private final Assignment cLeftCardinalityAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLeftCardinalityMultiplicityParserRuleCall_2_0 = (RuleCall)cLeftCardinalityAssignment_2.eContents().get(0);
		private final Assignment cLeftDecoratorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLeftDecoratorLineDecoratorParserRuleCall_3_0 = (RuleCall)cLeftDecoratorAssignment_3.eContents().get(0);
		private final Assignment cLineAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLineLineParserRuleCall_4_0 = (RuleCall)cLineAssignment_4.eContents().get(0);
		private final Assignment cRightDecoratorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRightDecoratorLineDecoratorParserRuleCall_5_0 = (RuleCall)cRightDecoratorAssignment_5.eContents().get(0);
		private final Assignment cRightCardinalityAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRightCardinalityMultiplicityParserRuleCall_6_0 = (RuleCall)cRightCardinalityAssignment_6.eContents().get(0);
		private final Assignment cRightAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cRightClassCrossReference_7_0 = (CrossReference)cRightAssignment_7.eContents().get(0);
		private final RuleCall cRightClassFQNParserRuleCall_7_0_1 = (RuleCall)cRightClassCrossReference_7_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cLabelAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cLabelLabelParserRuleCall_8_1_0 = (RuleCall)cLabelAssignment_8_1.eContents().get(0);
		
		//Relationship:
		//    {Relationship}
		//    left=[Class|FQN]
		//    (leftCardinality=Multiplicity)?
		//    (leftDecorator=LineDecorator)?
		//    (line=Line)
		//    (rightDecorator=LineDecorator)?
		//    (rightCardinality=Multiplicity)?
		//    right=[Class | FQN]
		//    (':' label=Label)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Relationship}
		//left=[Class|FQN]
		//(leftCardinality=Multiplicity)?
		//(leftDecorator=LineDecorator)?
		//(line=Line)
		//(rightDecorator=LineDecorator)?
		//(rightCardinality=Multiplicity)?
		//right=[Class | FQN]
		//(':' label=Label)?
		public Group getGroup() { return cGroup; }
		
		//{Relationship}
		public Action getRelationshipAction_0() { return cRelationshipAction_0; }
		
		//left=[Class|FQN]
		public Assignment getLeftAssignment_1() { return cLeftAssignment_1; }
		
		//[Class|FQN]
		public CrossReference getLeftClassCrossReference_1_0() { return cLeftClassCrossReference_1_0; }
		
		//FQN
		public RuleCall getLeftClassFQNParserRuleCall_1_0_1() { return cLeftClassFQNParserRuleCall_1_0_1; }
		
		//(leftCardinality=Multiplicity)?
		public Assignment getLeftCardinalityAssignment_2() { return cLeftCardinalityAssignment_2; }
		
		//Multiplicity
		public RuleCall getLeftCardinalityMultiplicityParserRuleCall_2_0() { return cLeftCardinalityMultiplicityParserRuleCall_2_0; }
		
		//(leftDecorator=LineDecorator)?
		public Assignment getLeftDecoratorAssignment_3() { return cLeftDecoratorAssignment_3; }
		
		//LineDecorator
		public RuleCall getLeftDecoratorLineDecoratorParserRuleCall_3_0() { return cLeftDecoratorLineDecoratorParserRuleCall_3_0; }
		
		//(line=Line)
		public Assignment getLineAssignment_4() { return cLineAssignment_4; }
		
		//Line
		public RuleCall getLineLineParserRuleCall_4_0() { return cLineLineParserRuleCall_4_0; }
		
		//(rightDecorator=LineDecorator)?
		public Assignment getRightDecoratorAssignment_5() { return cRightDecoratorAssignment_5; }
		
		//LineDecorator
		public RuleCall getRightDecoratorLineDecoratorParserRuleCall_5_0() { return cRightDecoratorLineDecoratorParserRuleCall_5_0; }
		
		//(rightCardinality=Multiplicity)?
		public Assignment getRightCardinalityAssignment_6() { return cRightCardinalityAssignment_6; }
		
		//Multiplicity
		public RuleCall getRightCardinalityMultiplicityParserRuleCall_6_0() { return cRightCardinalityMultiplicityParserRuleCall_6_0; }
		
		//right=[Class | FQN]
		public Assignment getRightAssignment_7() { return cRightAssignment_7; }
		
		//[Class | FQN]
		public CrossReference getRightClassCrossReference_7_0() { return cRightClassCrossReference_7_0; }
		
		//FQN
		public RuleCall getRightClassFQNParserRuleCall_7_0_1() { return cRightClassFQNParserRuleCall_7_0_1; }
		
		//(':' label=Label)?
		public Group getGroup_8() { return cGroup_8; }
		
		//':'
		public Keyword getColonKeyword_8_0() { return cColonKeyword_8_0; }
		
		//label=Label
		public Assignment getLabelAssignment_8_1() { return cLabelAssignment_8_1; }
		
		//Label
		public RuleCall getLabelLabelParserRuleCall_8_1_0() { return cLabelLabelParserRuleCall_8_1_0; }
	}
	public class MultiplicityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Multiplicity");
		private final RuleCall cDOUBLE_QUOTED_STRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Multiplicity:
		//    DOUBLE_QUOTED_STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//DOUBLE_QUOTED_STRING
		public RuleCall getDOUBLE_QUOTED_STRINGTerminalRuleCall() { return cDOUBLE_QUOTED_STRINGTerminalRuleCall; }
	}
	public class LineDecoratorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.LineDecorator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cLessThanSignVerticalLineKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cVerticalLineGreaterThanSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cOKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cAsteriskKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cLessThanSignKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cGreaterThanSignKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//LineDecorator:
		//    '<|' | '|>' | 'o' | '*' | '<' | '>'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'<|' | '|>' | 'o' | '*' | '<' | '>'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'<|'
		public Keyword getLessThanSignVerticalLineKeyword_0() { return cLessThanSignVerticalLineKeyword_0; }
		
		//'|>'
		public Keyword getVerticalLineGreaterThanSignKeyword_1() { return cVerticalLineGreaterThanSignKeyword_1; }
		
		//'o'
		public Keyword getOKeyword_2() { return cOKeyword_2; }
		
		//'*'
		public Keyword getAsteriskKeyword_3() { return cAsteriskKeyword_3; }
		
		//'<'
		public Keyword getLessThanSignKeyword_4() { return cLessThanSignKeyword_4; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_5() { return cGreaterThanSignKeyword_5; }
	}
	public class LineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Line");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cHyphenMinusHyphenMinusKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cFullStopFullStopKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cFullStopKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//Line:
		//    '--' | '-' | '..' | '.'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'--' | '-' | '..' | '.'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'--'
		public Keyword getHyphenMinusHyphenMinusKeyword_0() { return cHyphenMinusHyphenMinusKeyword_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//'..'
		public Keyword getFullStopFullStopKeyword_2() { return cFullStopFullStopKeyword_2; }
		
		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
	}
	public class LabelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Label");
		private final RuleCall cIDTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Label:
		//    ID+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ID+
		public RuleCall getIDTerminalRuleCall() { return cIDTerminalRuleCall; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPrimitiveTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cReferTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Type:
		//    PrimitiveType | ReferType;
		@Override public ParserRule getRule() { return rule; }
		
		//PrimitiveType | ReferType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PrimitiveType
		public RuleCall getPrimitiveTypeParserRuleCall_0() { return cPrimitiveTypeParserRuleCall_0; }
		
		//ReferType
		public RuleCall getReferTypeParserRuleCall_1() { return cReferTypeParserRuleCall_1; }
	}
	public class PrimitiveTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.PrimitiveType");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cNameAlternatives_0 = (Alternatives)cNameAssignment.eContents().get(0);
		private final Keyword cNameBooleanKeyword_0_0 = (Keyword)cNameAlternatives_0.eContents().get(0);
		private final Keyword cNameIntegerKeyword_0_1 = (Keyword)cNameAlternatives_0.eContents().get(1);
		private final Keyword cNameRealKeyword_0_2 = (Keyword)cNameAlternatives_0.eContents().get(2);
		private final Keyword cNameStringKeyword_0_3 = (Keyword)cNameAlternatives_0.eContents().get(3);
		private final Keyword cNameDoubleKeyword_0_4 = (Keyword)cNameAlternatives_0.eContents().get(4);
		private final Keyword cNameUnlimitedNaturalKeyword_0_5 = (Keyword)cNameAlternatives_0.eContents().get(5);
		private final Keyword cNameDateKeyword_0_6 = (Keyword)cNameAlternatives_0.eContents().get(6);
		private final Keyword cNameVoidKeyword_0_7 = (Keyword)cNameAlternatives_0.eContents().get(7);
		private final Keyword cNameIntKeyword_0_8 = (Keyword)cNameAlternatives_0.eContents().get(8);
		private final Keyword cNameBooleanKeyword_0_9 = (Keyword)cNameAlternatives_0.eContents().get(9);
		private final Keyword cNameDoubleKeyword_0_10 = (Keyword)cNameAlternatives_0.eContents().get(10);
		
		//PrimitiveType:
		//    name=('Boolean' | 'Integer' | 'Real' | 'String' | 'Double'
		//        | 'UnlimitedNatural' | 'Date'
		//        | 'void' | 'int'| 'boolean' | 'double'
		//        )
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=('Boolean' | 'Integer' | 'Real' | 'String' | 'Double'
		//    | 'UnlimitedNatural' | 'Date'
		//    | 'void' | 'int'| 'boolean' | 'double'
		//    )
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//('Boolean' | 'Integer' | 'Real' | 'String' | 'Double'
		//        | 'UnlimitedNatural' | 'Date'
		//        | 'void' | 'int'| 'boolean' | 'double'
		//        )
		public Alternatives getNameAlternatives_0() { return cNameAlternatives_0; }
		
		//'Boolean'
		public Keyword getNameBooleanKeyword_0_0() { return cNameBooleanKeyword_0_0; }
		
		//'Integer'
		public Keyword getNameIntegerKeyword_0_1() { return cNameIntegerKeyword_0_1; }
		
		//'Real'
		public Keyword getNameRealKeyword_0_2() { return cNameRealKeyword_0_2; }
		
		//'String'
		public Keyword getNameStringKeyword_0_3() { return cNameStringKeyword_0_3; }
		
		//'Double'
		public Keyword getNameDoubleKeyword_0_4() { return cNameDoubleKeyword_0_4; }
		
		//'UnlimitedNatural'
		public Keyword getNameUnlimitedNaturalKeyword_0_5() { return cNameUnlimitedNaturalKeyword_0_5; }
		
		//'Date'
		public Keyword getNameDateKeyword_0_6() { return cNameDateKeyword_0_6; }
		
		//'void'
		public Keyword getNameVoidKeyword_0_7() { return cNameVoidKeyword_0_7; }
		
		//'int'
		public Keyword getNameIntKeyword_0_8() { return cNameIntKeyword_0_8; }
		
		//'boolean'
		public Keyword getNameBooleanKeyword_0_9() { return cNameBooleanKeyword_0_9; }
		
		//'double'
		public Keyword getNameDoubleKeyword_0_10() { return cNameDoubleKeyword_0_10; }
	}
	public class ReferTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.ReferType");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//ReferType:
		//    name=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class EnumItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.EnumItem");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameSimpleNameParserRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//EnumItem:
		//    name=SimpleName
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=SimpleName
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//SimpleName
		public RuleCall getNameSimpleNameParserRuleCall_0() { return cNameSimpleNameParserRuleCall_0; }
	}
	public class EnumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.Enum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEnumAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEnumKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSimpleNameParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cValuesAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cValuesEnumItemParserRuleCall_4_0_0 = (RuleCall)cValuesAssignment_4_0.eContents().get(0);
		private final Assignment cValuesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValuesEnumItemParserRuleCall_4_1_0 = (RuleCall)cValuesAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Enum:
		//    {Enum}
		//    'enum' name=SimpleName '{'
		//    (values += EnumItem (values += EnumItem)*)
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Enum}
		//'enum' name=SimpleName '{'
		//(values += EnumItem (values += EnumItem)*)
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Enum}
		public Action getEnumAction_0() { return cEnumAction_0; }
		
		//'enum'
		public Keyword getEnumKeyword_1() { return cEnumKeyword_1; }
		
		//name=SimpleName
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//SimpleName
		public RuleCall getNameSimpleNameParserRuleCall_2_0() { return cNameSimpleNameParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(values += EnumItem (values += EnumItem)*)
		public Group getGroup_4() { return cGroup_4; }
		
		//values += EnumItem
		public Assignment getValuesAssignment_4_0() { return cValuesAssignment_4_0; }
		
		//EnumItem
		public RuleCall getValuesEnumItemParserRuleCall_4_0_0() { return cValuesEnumItemParserRuleCall_4_0_0; }
		
		//(values += EnumItem)*
		public Assignment getValuesAssignment_4_1() { return cValuesAssignment_4_1; }
		
		//EnumItem
		public RuleCall getValuesEnumItemParserRuleCall_4_1_0() { return cValuesEnumItemParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private final ClassDiagramElements pClassDiagram;
	private final AbstractElementElements pAbstractElement;
	private final PackageDeclarationElements pPackageDeclaration;
	private final FQNElements pFQN;
	private final ClassElements pClass;
	private final InterfaceElements pInterface;
	private final AbstractClassElements pAbstractClass;
	private final SimpleNameElements pSimpleName;
	private final AttributeElements pAttribute;
	private final OperationElements pOperation;
	private final ParameterElements pParameter;
	private final VisibilityElements pVisibility;
	private final RelationshipElements pRelationship;
	private final MultiplicityElements pMultiplicity;
	private final LineDecoratorElements pLineDecorator;
	private final LineElements pLine;
	private final LabelElements pLabel;
	private final TypeElements pType;
	private final PrimitiveTypeElements pPrimitiveType;
	private final ReferTypeElements pReferType;
	private final EnumItemElements pEnumItem;
	private final EnumElements pEnum;
	private final TerminalRule tDOUBLE_QUOTED_STRING;
	private final TerminalRule tESCAPED_CHARACTER;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ClassDiagramGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pClassDiagram = new ClassDiagramElements();
		this.pAbstractElement = new AbstractElementElements();
		this.pPackageDeclaration = new PackageDeclarationElements();
		this.pFQN = new FQNElements();
		this.pClass = new ClassElements();
		this.pInterface = new InterfaceElements();
		this.pAbstractClass = new AbstractClassElements();
		this.pSimpleName = new SimpleNameElements();
		this.pAttribute = new AttributeElements();
		this.pOperation = new OperationElements();
		this.pParameter = new ParameterElements();
		this.pVisibility = new VisibilityElements();
		this.pRelationship = new RelationshipElements();
		this.pMultiplicity = new MultiplicityElements();
		this.pLineDecorator = new LineDecoratorElements();
		this.pLine = new LineElements();
		this.pLabel = new LabelElements();
		this.pType = new TypeElements();
		this.pPrimitiveType = new PrimitiveTypeElements();
		this.pReferType = new ReferTypeElements();
		this.pEnumItem = new EnumItemElements();
		this.pEnum = new EnumElements();
		this.tDOUBLE_QUOTED_STRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.DOUBLE_QUOTED_STRING");
		this.tESCAPED_CHARACTER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "com.rm2pt.rapidood.cd.ClassDiagram.ESCAPED_CHARACTER");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.rm2pt.rapidood.cd.ClassDiagram".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//ClassDiagram:
	//    {ClassDiagram}
	//    '@startuml'
	//    (elements += AbstractElement)*
	//    '@enduml'
	//;
	public ClassDiagramElements getClassDiagramAccess() {
		return pClassDiagram;
	}
	
	public ParserRule getClassDiagramRule() {
		return getClassDiagramAccess().getRule();
	}
	
	//AbstractElement:
	//    PackageDeclaration | Class | Interface | AbstractClass | Relationship | Enum
	//;
	public AbstractElementElements getAbstractElementAccess() {
		return pAbstractElement;
	}
	
	public ParserRule getAbstractElementRule() {
		return getAbstractElementAccess().getRule();
	}
	
	//PackageDeclaration:
	//    'package' name=FQN '{'
	//            (elements += AbstractElement)*
	//    '}'
	//;
	public PackageDeclarationElements getPackageDeclarationAccess() {
		return pPackageDeclaration;
	}
	
	public ParserRule getPackageDeclarationRule() {
		return getPackageDeclarationAccess().getRule();
	}
	
	//FQN:
	//    ID (=>'.' ID)*;
	public FQNElements getFQNAccess() {
		return pFQN;
	}
	
	public ParserRule getFQNRule() {
		return getFQNAccess().getRule();
	}
	
	//Class:
	//    'class' name=SimpleName '{'
	//            (attributes += Attribute)*
	//            (operations += Operation)*
	//    '}';
	public ClassElements getClassAccess() {
		return pClass;
	}
	
	public ParserRule getClassRule() {
		return getClassAccess().getRule();
	}
	
	//Interface:
	//    'interface' name=SimpleName '{'
	//            (attributes += Attribute)*
	//            (operations += Operation)*
	//    '}';
	public InterfaceElements getInterfaceAccess() {
		return pInterface;
	}
	
	public ParserRule getInterfaceRule() {
		return getInterfaceAccess().getRule();
	}
	
	//AbstractClass:
	//    ('abstract') ('class')? name=SimpleName '{'
	//            (attributes += Attribute)*
	//            (operations += Operation)*
	//    '}';
	public AbstractClassElements getAbstractClassAccess() {
		return pAbstractClass;
	}
	
	public ParserRule getAbstractClassRule() {
		return getAbstractClassAccess().getRule();
	}
	
	//SimpleName hidden():
	//    ID;
	public SimpleNameElements getSimpleNameAccess() {
		return pSimpleName;
	}
	
	public ParserRule getSimpleNameRule() {
		return getSimpleNameAccess().getRule();
	}
	
	//Attribute:
	//    visibility=Visibility? (isStatic?='{static}')? name=SimpleName ':' type=Type;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//Operation:
	//    visibility=Visibility? (isAbstract?='{abstract}')? (isStatic?='{static}')?
	//    name=SimpleName '(' (params+=Parameter (',' params+=Parameter)*)? ')' ':' returnType=Type;
	public OperationElements getOperationAccess() {
		return pOperation;
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}
	
	//Parameter:
	//    type=Type name=SimpleName;
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//Visibility:
	//    '+' | '-' | '#' | '~';
	public VisibilityElements getVisibilityAccess() {
		return pVisibility;
	}
	
	public ParserRule getVisibilityRule() {
		return getVisibilityAccess().getRule();
	}
	
	//Relationship:
	//    {Relationship}
	//    left=[Class|FQN]
	//    (leftCardinality=Multiplicity)?
	//    (leftDecorator=LineDecorator)?
	//    (line=Line)
	//    (rightDecorator=LineDecorator)?
	//    (rightCardinality=Multiplicity)?
	//    right=[Class | FQN]
	//    (':' label=Label)?
	//;
	public RelationshipElements getRelationshipAccess() {
		return pRelationship;
	}
	
	public ParserRule getRelationshipRule() {
		return getRelationshipAccess().getRule();
	}
	
	//Multiplicity:
	//    DOUBLE_QUOTED_STRING
	//;
	public MultiplicityElements getMultiplicityAccess() {
		return pMultiplicity;
	}
	
	public ParserRule getMultiplicityRule() {
		return getMultiplicityAccess().getRule();
	}
	
	//LineDecorator:
	//    '<|' | '|>' | 'o' | '*' | '<' | '>'
	//;
	public LineDecoratorElements getLineDecoratorAccess() {
		return pLineDecorator;
	}
	
	public ParserRule getLineDecoratorRule() {
		return getLineDecoratorAccess().getRule();
	}
	
	//Line:
	//    '--' | '-' | '..' | '.'
	//;
	public LineElements getLineAccess() {
		return pLine;
	}
	
	public ParserRule getLineRule() {
		return getLineAccess().getRule();
	}
	
	//Label:
	//    ID+
	//;
	public LabelElements getLabelAccess() {
		return pLabel;
	}
	
	public ParserRule getLabelRule() {
		return getLabelAccess().getRule();
	}
	
	//Type:
	//    PrimitiveType | ReferType;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//PrimitiveType:
	//    name=('Boolean' | 'Integer' | 'Real' | 'String' | 'Double'
	//        | 'UnlimitedNatural' | 'Date'
	//        | 'void' | 'int'| 'boolean' | 'double'
	//        )
	//;
	public PrimitiveTypeElements getPrimitiveTypeAccess() {
		return pPrimitiveType;
	}
	
	public ParserRule getPrimitiveTypeRule() {
		return getPrimitiveTypeAccess().getRule();
	}
	
	//ReferType:
	//    name=ID
	//;
	public ReferTypeElements getReferTypeAccess() {
		return pReferType;
	}
	
	public ParserRule getReferTypeRule() {
		return getReferTypeAccess().getRule();
	}
	
	//EnumItem:
	//    name=SimpleName
	//;
	public EnumItemElements getEnumItemAccess() {
		return pEnumItem;
	}
	
	public ParserRule getEnumItemRule() {
		return getEnumItemAccess().getRule();
	}
	
	//Enum:
	//    {Enum}
	//    'enum' name=SimpleName '{'
	//    (values += EnumItem (values += EnumItem)*)
	//    '}'
	//;
	public EnumElements getEnumAccess() {
		return pEnum;
	}
	
	public ParserRule getEnumRule() {
		return getEnumAccess().getRule();
	}
	
	//terminal DOUBLE_QUOTED_STRING:
	//    '"' (ESCAPED_CHARACTER | !('\\' | '"' | '.'))* '"';
	public TerminalRule getDOUBLE_QUOTED_STRINGRule() {
		return tDOUBLE_QUOTED_STRING;
	}
	
	//terminal fragment ESCAPED_CHARACTER:
	//    '\\' ('b' | 't' | 'n' | 'f' | 'r' | 'u' | '"' | "'" | '\\');
	public TerminalRule getESCAPED_CHARACTERRule() {
		return tESCAPED_CHARACTER;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
