/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.rm2pt.rapidood.cd.ClassDiagramRuntimeModule;
import com.rm2pt.rapidood.cd.ClassDiagramStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ClassDiagramIdeSetup extends ClassDiagramStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ClassDiagramRuntimeModule(), new ClassDiagramIdeModule()));
	}
	
}
