/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.scoping;

import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.naming.QualifiedName;

import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.resource.Resource;
import com.rm2pt.rapidood.cd.classDiagram.*;
import com.rm2pt.rapidood.cd.classDiagram.Class;
import com.rm2pt.rapidood.cd.classDiagram.Enum;

import org.eclipse.xtext.EcoreUtil2;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ClassDiagramScopeProvider extends AbstractClassDiagramScopeProvider {
    @Override
    public IScope getScope(EObject context, EReference reference) {
    	Resource resource = context.eResource();
        ClassDiagram root = (ClassDiagram) resource.getContents().get(0);
        // 处理Relationship中的Class引用
        if (context instanceof Relationship) {
            // 获取当前Relationship所在的包（可能为null，表示根包）
            PackageDeclaration currentPackage = EcoreUtil2.getContainerOfType(context, PackageDeclaration.class);
            // 作用域1：其他包的类（使用FQN）
            // 获取所有已定义的Class（包含包路径）
            List<Class> allClasses = EcoreUtil2.eAllOfType(root, Class.class);
            List<Class> otherClasses = allClasses.stream()
                    .filter(cls -> !isInPackage(cls, currentPackage))
                    .collect(Collectors.toList());
            IScope globalScope = Scopes.scopeFor(otherClasses, 
                cls -> QualifiedName.create(getFullyQualifiedName(cls).split("\\.")), 
                IScope.NULLSCOPE
            );
	        
            // 全局允许简单名称，忽略了不同包下同名类的情况
            IScope currentPackageScope = Scopes.scopeFor(allClasses, 
	            cls -> QualifiedName.create(cls.getName()), 
	            globalScope
	        );
            // 作用域2：当前包内的类（使用简单名称）
//            List<Class> currentPackageClasses = getClassesInPackage(currentPackage, context);
//            IScope currentPackageScope = Scopes.scopeFor(currentPackageClasses, 
//                cls -> QualifiedName.create(cls.getName()), 
//                globalScope
//            );
//        	
            return currentPackageScope;
        }
        // 处理Type中的ReferType引用
        // TODO:现在实际上还做不到为ReferType支持全限定名称，因为在语法上就不允许
        // 如果想要实现，可能需要修改ReferType中Class和Enum支持通过FQN访问
        else if (context instanceof ReferType) {
        	// 获取当前ReferType所在的包（可能为null，表示根包）
        	PackageDeclaration currentPackage = EcoreUtil2.getContainerOfType(context, PackageDeclaration.class);
        	
            // 作用域1：其他包的类和Enum（使用FQN）
        	// 获取所有Class和Enum的声明
        	List<EObject> otherPackageElements = getClassesAndEnumsOutsidePackage(currentPackage, context);
            
            IScope globalScope = Scopes.scopeFor(otherPackageElements, 
                // e -> QualifiedName.create(getFullyQualifiedName(e).split("\\.")),
            	e -> QualifiedName.create(getName(e)),
                IScope.NULLSCOPE
            );
            // 作用域2：当钱包内的类和Enum（使用简单名称）
            List<EObject> currentPackageElements = getClassesAndEnumsInPackage(currentPackage, context);
            IScope currentPackageScope = Scopes.scopeFor(currentPackageElements, 
                e -> QualifiedName.create(getName(e)), 
                globalScope
            );
            return currentPackageScope;
        }
        return super.getScope(context, reference);
    }
    // 获取当前包内的所有Class
    private List<Class> getClassesInPackage(PackageDeclaration pkg, EObject context) {
    	Resource resource = context.eResource();
        ClassDiagram root = (ClassDiagram) resource.getContents().get(0);
        if (pkg == null) {
            // 根包下的类
            return EcoreUtil2.eAllOfType(root, Class.class).stream()
                .filter(cls -> cls.eContainer() instanceof ClassDiagram)
                .collect(Collectors.toList());
        }
        return EcoreUtil2.eAllOfType(pkg, Class.class);
    }
    // 获取包外Class和Enum
    private List<EObject> getClassesAndEnumsOutsidePackage(PackageDeclaration currentPackage, EObject context) {
    	Resource resource = context.eResource();
        ClassDiagram root = (ClassDiagram) resource.getContents().get(0);
        List<EObject> allElements = EcoreUtil2.eAllOfType(root, AbstractElement.class).stream()
            .filter(e -> e instanceof Class || e instanceof Enum) // 后续如果有更多引用的对象，可以直接在这里添加
            .collect(Collectors.toList());
            
        return allElements.stream()
            .filter(e -> !isInPackage(e, currentPackage))
            .collect(Collectors.toList());
    }
    // 获取当前包内的Class和Enum
    private List<EObject> getClassesAndEnumsInPackage(PackageDeclaration pkg, EObject context) {
    	Resource resource = context.eResource();
        ClassDiagram root = (ClassDiagram) resource.getContents().get(0);
        if (pkg == null) {
            // 根包下的元素
            return EcoreUtil2.eAllOfType(root, AbstractElement.class).stream()
                .filter(e -> (e instanceof Class || e instanceof Enum) 
                    && e.eContainer() instanceof ClassDiagram)
                .collect(Collectors.toList());
        }
        return EcoreUtil2.eAllOfType(pkg, AbstractElement.class).stream()
            .filter(e -> e instanceof Class || e instanceof Enum)
            .collect(Collectors.toList());
    }
    // 检查元素是否在指定包内
    private boolean isInPackage(EObject element, PackageDeclaration pkg) {
        if (pkg == null) {
            // 当前无包时，检查是否在根包
            return element.eContainer() instanceof ClassDiagram;
        }
        return EcoreUtil2.isAncestor(pkg, element);
    }
    // 递归获取元素的FQN（考虑包嵌套）
    private String getFullyQualifiedName(EObject obj) {
        if (obj.eContainer() instanceof PackageDeclaration) {
            PackageDeclaration pkg = (PackageDeclaration) obj.eContainer();
            return getFullyQualifiedName(pkg) + "." + getName(obj);
        }
        return getName(obj);
    }

    // 获取元素名称（统一处理Class、Enum等）
    private String getName(EObject obj) {
        if (obj instanceof Class) {
            return ((Class) obj).getName();
        } else if (obj instanceof Enum) {
            return ((Enum) obj).getName();
        } else if (obj instanceof PackageDeclaration) {
            return ((PackageDeclaration) obj).getName();
        } 
        return "";
    }
}
