/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.model.XtextDocumentProvider;
import com.rm2pt.rapidood.cd.ui.extra.ClassDiagramDocumentProvider;
/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ClassDiagramUiModule extends AbstractClassDiagramUiModule {

	public ClassDiagramUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends XtextDocumentProvider> bindXtextDocumentProvider() {
		return ClassDiagramDocumentProvider.class;
	}
}
