/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractClassDiagramScopeProvider extends DelegatingScopeProvider {
}
