/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.classDiagram;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramFactory
 * @model kind="package"
 * @generated
 */
public interface ClassDiagramPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "classDiagram";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.rm2pt.com/rapidood/cd/ClassDiagram";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "classDiagram";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ClassDiagramPackage eINSTANCE = com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl.init();

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramImpl <em>Class Diagram</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getClassDiagram()
   * @generated
   */
  int CLASS_DIAGRAM = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DIAGRAM__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Class Diagram</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DIAGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.AbstractElementImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.PackageDeclarationImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getPackageDeclaration()
   * @generated
   */
  int PACKAGE_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__ELEMENTS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Package Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.ClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getClass_()
   * @generated
   */
  int CLASS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__ATTRIBUTES = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__OPERATIONS = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.InterfaceImpl <em>Interface</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.InterfaceImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getInterface()
   * @generated
   */
  int INTERFACE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__ATTRIBUTES = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__OPERATIONS = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Interface</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.AbstractClassImpl <em>Abstract Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.AbstractClassImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getAbstractClass()
   * @generated
   */
  int ABSTRACT_CLASS = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CLASS__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CLASS__ATTRIBUTES = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CLASS__OPERATIONS = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Abstract Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CLASS_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.AttributeImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 6;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__VISIBILITY = 0;

  /**
   * The feature id for the '<em><b>Is Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__IS_STATIC = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 3;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.OperationImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 7;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__VISIBILITY = 0;

  /**
   * The feature id for the '<em><b>Is Abstract</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__IS_ABSTRACT = 1;

  /**
   * The feature id for the '<em><b>Is Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__IS_STATIC = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__NAME = 3;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__PARAMS = 4;

  /**
   * The feature id for the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__RETURN_TYPE = 5;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ParameterImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 8;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 1;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl <em>Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getRelationship()
   * @generated
   */
  int RELATIONSHIP = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__LEFT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Left Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__LEFT_CARDINALITY = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Left Decorator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__LEFT_DECORATOR = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Line</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__LINE = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Right Decorator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__RIGHT_DECORATOR = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Right Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__RIGHT_CARDINALITY = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Right</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__RIGHT = ABSTRACT_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__LABEL = ABSTRACT_ELEMENT_FEATURE_COUNT + 7;

  /**
   * The number of structural features of the '<em>Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 8;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.TypeImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getType()
   * @generated
   */
  int TYPE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.PrimitiveTypeImpl <em>Primitive Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.PrimitiveTypeImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getPrimitiveType()
   * @generated
   */
  int PRIMITIVE_TYPE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Primitive Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.ReferTypeImpl <em>Refer Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ReferTypeImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getReferType()
   * @generated
   */
  int REFER_TYPE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFER_TYPE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Refer Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFER_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.EnumItemImpl <em>Enum Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.EnumItemImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getEnumItem()
   * @generated
   */
  int ENUM_ITEM = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_ITEM__NAME = 0;

  /**
   * The number of structural features of the '<em>Enum Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_ITEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.EnumImpl <em>Enum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.EnumImpl
   * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getEnum()
   * @generated
   */
  int ENUM = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM__VALUES = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Enum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.ClassDiagram <em>Class Diagram</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Diagram</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagram
   * @generated
   */
  EClass getClassDiagram();

  /**
   * Returns the meta object for the containment reference list '{@link com.rm2pt.rapidood.cd.classDiagram.ClassDiagram#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagram#getElements()
   * @see #getClassDiagram()
   * @generated
   */
  EReference getClassDiagram_Elements();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.PackageDeclaration <em>Package Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Declaration</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.PackageDeclaration
   * @generated
   */
  EClass getPackageDeclaration();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.PackageDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.PackageDeclaration#getName()
   * @see #getPackageDeclaration()
   * @generated
   */
  EAttribute getPackageDeclaration_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.rm2pt.rapidood.cd.classDiagram.PackageDeclaration#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.PackageDeclaration#getElements()
   * @see #getPackageDeclaration()
   * @generated
   */
  EReference getPackageDeclaration_Elements();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.Class <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Class
   * @generated
   */
  EClass getClass_();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Class#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Class#getName()
   * @see #getClass_()
   * @generated
   */
  EAttribute getClass_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.rm2pt.rapidood.cd.classDiagram.Class#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Class#getAttributes()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link com.rm2pt.rapidood.cd.classDiagram.Class#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Class#getOperations()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Operations();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.Interface <em>Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interface</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Interface
   * @generated
   */
  EClass getInterface();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Interface#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Interface#getName()
   * @see #getInterface()
   * @generated
   */
  EAttribute getInterface_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.rm2pt.rapidood.cd.classDiagram.Interface#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Interface#getAttributes()
   * @see #getInterface()
   * @generated
   */
  EReference getInterface_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link com.rm2pt.rapidood.cd.classDiagram.Interface#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Interface#getOperations()
   * @see #getInterface()
   * @generated
   */
  EReference getInterface_Operations();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.AbstractClass <em>Abstract Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Class</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.AbstractClass
   * @generated
   */
  EClass getAbstractClass();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.AbstractClass#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.AbstractClass#getName()
   * @see #getAbstractClass()
   * @generated
   */
  EAttribute getAbstractClass_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.rm2pt.rapidood.cd.classDiagram.AbstractClass#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.AbstractClass#getAttributes()
   * @see #getAbstractClass()
   * @generated
   */
  EReference getAbstractClass_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link com.rm2pt.rapidood.cd.classDiagram.AbstractClass#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.AbstractClass#getOperations()
   * @see #getAbstractClass()
   * @generated
   */
  EReference getAbstractClass_Operations();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Attribute#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Attribute#getVisibility()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Visibility();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Attribute#isIsStatic <em>Is Static</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Static</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Attribute#isIsStatic()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_IsStatic();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.rm2pt.rapidood.cd.classDiagram.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Type();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Operation#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Operation#getVisibility()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Visibility();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Operation#isIsAbstract <em>Is Abstract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Abstract</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Operation#isIsAbstract()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_IsAbstract();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Operation#isIsStatic <em>Is Static</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Static</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Operation#isIsStatic()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_IsStatic();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Operation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Operation#getName()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.rm2pt.rapidood.cd.classDiagram.Operation#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Operation#getParams()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Params();

  /**
   * Returns the meta object for the containment reference '{@link com.rm2pt.rapidood.cd.classDiagram.Operation#getReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return Type</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Operation#getReturnType()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_ReturnType();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the containment reference '{@link com.rm2pt.rapidood.cd.classDiagram.Parameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Parameter#getType()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Type();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relationship</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Relationship
   * @generated
   */
  EClass getRelationship();

  /**
   * Returns the meta object for the reference '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Left</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeft()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_Left();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeftCardinality <em>Left Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left Cardinality</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeftCardinality()
   * @see #getRelationship()
   * @generated
   */
  EAttribute getRelationship_LeftCardinality();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeftDecorator <em>Left Decorator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left Decorator</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeftDecorator()
   * @see #getRelationship()
   * @generated
   */
  EAttribute getRelationship_LeftDecorator();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLine <em>Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Line</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Relationship#getLine()
   * @see #getRelationship()
   * @generated
   */
  EAttribute getRelationship_Line();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getRightDecorator <em>Right Decorator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right Decorator</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Relationship#getRightDecorator()
   * @see #getRelationship()
   * @generated
   */
  EAttribute getRelationship_RightDecorator();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getRightCardinality <em>Right Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right Cardinality</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Relationship#getRightCardinality()
   * @see #getRelationship()
   * @generated
   */
  EAttribute getRelationship_RightCardinality();

  /**
   * Returns the meta object for the reference '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Right</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Relationship#getRight()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_Right();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Relationship#getLabel()
   * @see #getRelationship()
   * @generated
   */
  EAttribute getRelationship_Label();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.PrimitiveType <em>Primitive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primitive Type</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.PrimitiveType
   * @generated
   */
  EClass getPrimitiveType();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.ReferType <em>Refer Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Refer Type</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.ReferType
   * @generated
   */
  EClass getReferType();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.EnumItem <em>Enum Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Item</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.EnumItem
   * @generated
   */
  EClass getEnumItem();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.EnumItem#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.EnumItem#getName()
   * @see #getEnumItem()
   * @generated
   */
  EAttribute getEnumItem_Name();

  /**
   * Returns the meta object for class '{@link com.rm2pt.rapidood.cd.classDiagram.Enum <em>Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Enum
   * @generated
   */
  EClass getEnum();

  /**
   * Returns the meta object for the attribute '{@link com.rm2pt.rapidood.cd.classDiagram.Enum#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Enum#getName()
   * @see #getEnum()
   * @generated
   */
  EAttribute getEnum_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.rm2pt.rapidood.cd.classDiagram.Enum#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see com.rm2pt.rapidood.cd.classDiagram.Enum#getValues()
   * @see #getEnum()
   * @generated
   */
  EReference getEnum_Values();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ClassDiagramFactory getClassDiagramFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramImpl <em>Class Diagram</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getClassDiagram()
     * @generated
     */
    EClass CLASS_DIAGRAM = eINSTANCE.getClassDiagram();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DIAGRAM__ELEMENTS = eINSTANCE.getClassDiagram_Elements();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.AbstractElementImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.PackageDeclarationImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getPackageDeclaration()
     * @generated
     */
    EClass PACKAGE_DECLARATION = eINSTANCE.getPackageDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE_DECLARATION__NAME = eINSTANCE.getPackageDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE_DECLARATION__ELEMENTS = eINSTANCE.getPackageDeclaration_Elements();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.ClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getClass_()
     * @generated
     */
    EClass CLASS = eINSTANCE.getClass_();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS__NAME = eINSTANCE.getClass_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__ATTRIBUTES = eINSTANCE.getClass_Attributes();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__OPERATIONS = eINSTANCE.getClass_Operations();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.InterfaceImpl <em>Interface</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.InterfaceImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getInterface()
     * @generated
     */
    EClass INTERFACE = eINSTANCE.getInterface();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERFACE__NAME = eINSTANCE.getInterface_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERFACE__ATTRIBUTES = eINSTANCE.getInterface_Attributes();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERFACE__OPERATIONS = eINSTANCE.getInterface_Operations();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.AbstractClassImpl <em>Abstract Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.AbstractClassImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getAbstractClass()
     * @generated
     */
    EClass ABSTRACT_CLASS = eINSTANCE.getAbstractClass();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_CLASS__NAME = eINSTANCE.getAbstractClass_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_CLASS__ATTRIBUTES = eINSTANCE.getAbstractClass_Attributes();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_CLASS__OPERATIONS = eINSTANCE.getAbstractClass_Operations();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.AttributeImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__VISIBILITY = eINSTANCE.getAttribute_Visibility();

    /**
     * The meta object literal for the '<em><b>Is Static</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__IS_STATIC = eINSTANCE.getAttribute_IsStatic();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.OperationImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__VISIBILITY = eINSTANCE.getOperation_Visibility();

    /**
     * The meta object literal for the '<em><b>Is Abstract</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__IS_ABSTRACT = eINSTANCE.getOperation_IsAbstract();

    /**
     * The meta object literal for the '<em><b>Is Static</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__IS_STATIC = eINSTANCE.getOperation_IsStatic();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__NAME = eINSTANCE.getOperation_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__PARAMS = eINSTANCE.getOperation_Params();

    /**
     * The meta object literal for the '<em><b>Return Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__RETURN_TYPE = eINSTANCE.getOperation_ReturnType();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ParameterImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__TYPE = eINSTANCE.getParameter_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl <em>Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.RelationshipImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getRelationship()
     * @generated
     */
    EClass RELATIONSHIP = eINSTANCE.getRelationship();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__LEFT = eINSTANCE.getRelationship_Left();

    /**
     * The meta object literal for the '<em><b>Left Cardinality</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONSHIP__LEFT_CARDINALITY = eINSTANCE.getRelationship_LeftCardinality();

    /**
     * The meta object literal for the '<em><b>Left Decorator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONSHIP__LEFT_DECORATOR = eINSTANCE.getRelationship_LeftDecorator();

    /**
     * The meta object literal for the '<em><b>Line</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONSHIP__LINE = eINSTANCE.getRelationship_Line();

    /**
     * The meta object literal for the '<em><b>Right Decorator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONSHIP__RIGHT_DECORATOR = eINSTANCE.getRelationship_RightDecorator();

    /**
     * The meta object literal for the '<em><b>Right Cardinality</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONSHIP__RIGHT_CARDINALITY = eINSTANCE.getRelationship_RightCardinality();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__RIGHT = eINSTANCE.getRelationship_Right();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONSHIP__LABEL = eINSTANCE.getRelationship_Label();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.TypeImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.PrimitiveTypeImpl <em>Primitive Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.PrimitiveTypeImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getPrimitiveType()
     * @generated
     */
    EClass PRIMITIVE_TYPE = eINSTANCE.getPrimitiveType();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.ReferTypeImpl <em>Refer Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ReferTypeImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getReferType()
     * @generated
     */
    EClass REFER_TYPE = eINSTANCE.getReferType();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.EnumItemImpl <em>Enum Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.EnumItemImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getEnumItem()
     * @generated
     */
    EClass ENUM_ITEM = eINSTANCE.getEnumItem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_ITEM__NAME = eINSTANCE.getEnumItem_Name();

    /**
     * The meta object literal for the '{@link com.rm2pt.rapidood.cd.classDiagram.impl.EnumImpl <em>Enum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.EnumImpl
     * @see com.rm2pt.rapidood.cd.classDiagram.impl.ClassDiagramPackageImpl#getEnum()
     * @generated
     */
    EClass ENUM = eINSTANCE.getEnum();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM__NAME = eINSTANCE.getEnum_Name();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM__VALUES = eINSTANCE.getEnum_Values();

  }

} //ClassDiagramPackage
