/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.classDiagram;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Diagram</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.ClassDiagram#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getClassDiagram()
 * @model
 * @generated
 */
public interface ClassDiagram extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.rm2pt.rapidood.cd.classDiagram.AbstractElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getClassDiagram_Elements()
   * @model containment="true"
   * @generated
   */
  EList<AbstractElement> getElements();

} // ClassDiagram
