/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.classDiagram;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.Enum#getName <em>Name</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.Enum#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getEnum()
 * @model
 * @generated
 */
public interface Enum extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getEnum_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.rm2pt.rapidood.cd.classDiagram.Enum#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link com.rm2pt.rapidood.cd.classDiagram.EnumItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getEnum_Values()
   * @model containment="true"
   * @generated
   */
  EList<EnumItem> getValues();

} // Enum
