/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.classDiagram;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Refer Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getReferType()
 * @model
 * @generated
 */
public interface ReferType extends Type
{
} // ReferType
