/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.classDiagram;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeft <em>Left</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeftCardinality <em>Left Cardinality</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeftDecorator <em>Left Decorator</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLine <em>Line</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getRightDecorator <em>Right Decorator</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getRightCardinality <em>Right Cardinality</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getRight <em>Right</em>}</li>
 *   <li>{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLabel <em>Label</em>}</li>
 * </ul>
 *
 * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getRelationship()
 * @model
 * @generated
 */
public interface Relationship extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' reference.
   * @see #setLeft(com.rm2pt.rapidood.cd.classDiagram.Class)
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getRelationship_Left()
   * @model
   * @generated
   */
  com.rm2pt.rapidood.cd.classDiagram.Class getLeft();

  /**
   * Sets the value of the '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeft <em>Left</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(com.rm2pt.rapidood.cd.classDiagram.Class value);

  /**
   * Returns the value of the '<em><b>Left Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Cardinality</em>' attribute.
   * @see #setLeftCardinality(String)
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getRelationship_LeftCardinality()
   * @model
   * @generated
   */
  String getLeftCardinality();

  /**
   * Sets the value of the '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeftCardinality <em>Left Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Cardinality</em>' attribute.
   * @see #getLeftCardinality()
   * @generated
   */
  void setLeftCardinality(String value);

  /**
   * Returns the value of the '<em><b>Left Decorator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Decorator</em>' attribute.
   * @see #setLeftDecorator(String)
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getRelationship_LeftDecorator()
   * @model
   * @generated
   */
  String getLeftDecorator();

  /**
   * Sets the value of the '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLeftDecorator <em>Left Decorator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Decorator</em>' attribute.
   * @see #getLeftDecorator()
   * @generated
   */
  void setLeftDecorator(String value);

  /**
   * Returns the value of the '<em><b>Line</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line</em>' attribute.
   * @see #setLine(String)
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getRelationship_Line()
   * @model
   * @generated
   */
  String getLine();

  /**
   * Sets the value of the '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLine <em>Line</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Line</em>' attribute.
   * @see #getLine()
   * @generated
   */
  void setLine(String value);

  /**
   * Returns the value of the '<em><b>Right Decorator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Decorator</em>' attribute.
   * @see #setRightDecorator(String)
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getRelationship_RightDecorator()
   * @model
   * @generated
   */
  String getRightDecorator();

  /**
   * Sets the value of the '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getRightDecorator <em>Right Decorator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right Decorator</em>' attribute.
   * @see #getRightDecorator()
   * @generated
   */
  void setRightDecorator(String value);

  /**
   * Returns the value of the '<em><b>Right Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Cardinality</em>' attribute.
   * @see #setRightCardinality(String)
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getRelationship_RightCardinality()
   * @model
   * @generated
   */
  String getRightCardinality();

  /**
   * Sets the value of the '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getRightCardinality <em>Right Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right Cardinality</em>' attribute.
   * @see #getRightCardinality()
   * @generated
   */
  void setRightCardinality(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' reference.
   * @see #setRight(com.rm2pt.rapidood.cd.classDiagram.Class)
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getRelationship_Right()
   * @model
   * @generated
   */
  com.rm2pt.rapidood.cd.classDiagram.Class getRight();

  /**
   * Sets the value of the '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getRight <em>Right</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' reference.
   * @see #getRight()
   * @generated
   */
  void setRight(com.rm2pt.rapidood.cd.classDiagram.Class value);

  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage#getRelationship_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link com.rm2pt.rapidood.cd.classDiagram.Relationship#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

} // Relationship
