source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               GenerateClassDiagram.atl,\
               GenerateClassDiagram.asm
