/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.generator;

import com.google.inject.Inject;
import com.google.inject.Injector;
import com.rm2pt.rapidood.cd.formatting2.ClassDiagramFormatter;
import java.util.Collections;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.nodemodel.ICompositeNode;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.InputOutput;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class ClassDiagramGenerator extends AbstractGenerator {
  @Inject
  @Extension
  private /* ClassDiagramGrammarAccess */Object _classDiagramGrammarAccess;
  
  @Inject
  private ClassDiagramFormatter classDiagramFormatter;
  
  private static Injector injector;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    try {
      fsa.generateFile("ClassDiagramWithEntityManager.cd", this.getOriginalContent(resource));
      final URI tempUri = fsa.getURI("ClassDiagramWithEntityManager.cd");
      final ResourceSet resourceSet = ClassDiagramGenerator.getInjector().<ResourceSet>getInstance(ResourceSet.class);
      Resource _resource = resourceSet.getResource(tempUri, true);
      final XtextResource tempResource = ((XtextResource) _resource);
      tempResource.load(Collections.<Object, Object>emptyMap());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  public static synchronized Injector getInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type ClassDiagramStandaloneSetup");
  }
  
  public String getOriginalContent(final Resource resource) {
    String _xifexpression = null;
    if ((resource instanceof XtextResource)) {
      String _xblockexpression = null;
      {
        final XtextResource xtextResource = ((XtextResource) resource);
        final IParseResult parseResult = xtextResource.getParseResult();
        String _xifexpression_1 = null;
        if ((parseResult != null)) {
          final ICompositeNode rootNode = parseResult.getRootNode();
          final String textContent = rootNode.getText();
          return textContent;
        } else {
          _xifexpression_1 = InputOutput.<String>println("解析失败：AST未生成");
        }
        _xblockexpression = _xifexpression_1;
      }
      _xifexpression = _xblockexpression;
    } else {
      Class<? extends Resource> _class = null;
      if (resource!=null) {
        _class=resource.getClass();
      }
      String _simpleName = null;
      if (_class!=null) {
        _simpleName=_class.getSimpleName();
      }
      String _plus = ("非Xtext资源类型: " + _simpleName);
      _xifexpression = InputOutput.<String>println(_plus);
    }
    return _xifexpression;
  }
}
