/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractClassDiagramValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage.eINSTANCE);
		return result;
	}
}
