/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.serializer;

import com.google.inject.Inject;
import com.rm2pt.rapidood.cd.classDiagram.AbstractClass;
import com.rm2pt.rapidood.cd.classDiagram.Attribute;
import com.rm2pt.rapidood.cd.classDiagram.ClassDiagram;
import com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage;
import com.rm2pt.rapidood.cd.classDiagram.EnumItem;
import com.rm2pt.rapidood.cd.classDiagram.Interface;
import com.rm2pt.rapidood.cd.classDiagram.Operation;
import com.rm2pt.rapidood.cd.classDiagram.PackageDeclaration;
import com.rm2pt.rapidood.cd.classDiagram.PrimitiveType;
import com.rm2pt.rapidood.cd.classDiagram.ReferType;
import com.rm2pt.rapidood.cd.classDiagram.Relationship;
import com.rm2pt.rapidood.cd.services.ClassDiagramGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class ClassDiagramSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ClassDiagramGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ClassDiagramPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ClassDiagramPackage.ABSTRACT_CLASS:
				sequence_AbstractClass(context, (AbstractClass) semanticObject); 
				return; 
			case ClassDiagramPackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case ClassDiagramPackage.CLASS:
				sequence_Class(context, (com.rm2pt.rapidood.cd.classDiagram.Class) semanticObject); 
				return; 
			case ClassDiagramPackage.CLASS_DIAGRAM:
				sequence_ClassDiagram(context, (ClassDiagram) semanticObject); 
				return; 
			case ClassDiagramPackage.ENUM:
				sequence_Enum(context, (com.rm2pt.rapidood.cd.classDiagram.Enum) semanticObject); 
				return; 
			case ClassDiagramPackage.ENUM_ITEM:
				sequence_EnumItem(context, (EnumItem) semanticObject); 
				return; 
			case ClassDiagramPackage.INTERFACE:
				sequence_Interface(context, (Interface) semanticObject); 
				return; 
			case ClassDiagramPackage.OPERATION:
				sequence_Operation(context, (Operation) semanticObject); 
				return; 
			case ClassDiagramPackage.PACKAGE_DECLARATION:
				sequence_PackageDeclaration(context, (PackageDeclaration) semanticObject); 
				return; 
			case ClassDiagramPackage.PARAMETER:
				sequence_Parameter(context, (com.rm2pt.rapidood.cd.classDiagram.Parameter) semanticObject); 
				return; 
			case ClassDiagramPackage.PRIMITIVE_TYPE:
				sequence_PrimitiveType(context, (PrimitiveType) semanticObject); 
				return; 
			case ClassDiagramPackage.REFER_TYPE:
				sequence_ReferType(context, (ReferType) semanticObject); 
				return; 
			case ClassDiagramPackage.RELATIONSHIP:
				sequence_Relationship(context, (Relationship) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     AbstractElement returns AbstractClass
	 *     AbstractClass returns AbstractClass
	 *
	 * Constraint:
	 *     (name=SimpleName attributes+=Attribute* operations+=Operation*)
	 */
	protected void sequence_AbstractClass(ISerializationContext context, AbstractClass semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Attribute returns Attribute
	 *
	 * Constraint:
	 *     (visibility=Visibility? isStatic?='{static}'? name=SimpleName type=Type)
	 */
	protected void sequence_Attribute(ISerializationContext context, Attribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ClassDiagram returns ClassDiagram
	 *
	 * Constraint:
	 *     elements+=AbstractElement*
	 */
	protected void sequence_ClassDiagram(ISerializationContext context, ClassDiagram semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractElement returns Class
	 *     Class returns Class
	 *
	 * Constraint:
	 *     (name=SimpleName attributes+=Attribute* operations+=Operation*)
	 */
	protected void sequence_Class(ISerializationContext context, com.rm2pt.rapidood.cd.classDiagram.Class semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EnumItem returns EnumItem
	 *
	 * Constraint:
	 *     name=SimpleName
	 */
	protected void sequence_EnumItem(ISerializationContext context, EnumItem semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ClassDiagramPackage.Literals.ENUM_ITEM__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ClassDiagramPackage.Literals.ENUM_ITEM__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnumItemAccess().getNameSimpleNameParserRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AbstractElement returns Enum
	 *     Enum returns Enum
	 *
	 * Constraint:
	 *     (name=SimpleName values+=EnumItem values+=EnumItem*)
	 */
	protected void sequence_Enum(ISerializationContext context, com.rm2pt.rapidood.cd.classDiagram.Enum semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractElement returns Interface
	 *     Interface returns Interface
	 *
	 * Constraint:
	 *     (name=SimpleName attributes+=Attribute* operations+=Operation*)
	 */
	protected void sequence_Interface(ISerializationContext context, Interface semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Operation returns Operation
	 *
	 * Constraint:
	 *     (
	 *         visibility=Visibility? 
	 *         isAbstract?='{abstract}'? 
	 *         isStatic?='{static}'? 
	 *         name=SimpleName 
	 *         (params+=Parameter params+=Parameter*)? 
	 *         returnType=Type
	 *     )
	 */
	protected void sequence_Operation(ISerializationContext context, Operation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractElement returns PackageDeclaration
	 *     PackageDeclaration returns PackageDeclaration
	 *
	 * Constraint:
	 *     (name=FQN elements+=AbstractElement*)
	 */
	protected void sequence_PackageDeclaration(ISerializationContext context, PackageDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Parameter returns Parameter
	 *
	 * Constraint:
	 *     (type=Type name=SimpleName)
	 */
	protected void sequence_Parameter(ISerializationContext context, com.rm2pt.rapidood.cd.classDiagram.Parameter semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ClassDiagramPackage.Literals.PARAMETER__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ClassDiagramPackage.Literals.PARAMETER__TYPE));
			if (transientValues.isValueTransient(semanticObject, ClassDiagramPackage.Literals.PARAMETER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ClassDiagramPackage.Literals.PARAMETER__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParameterAccess().getTypeTypeParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getParameterAccess().getNameSimpleNameParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Type returns PrimitiveType
	 *     PrimitiveType returns PrimitiveType
	 *
	 * Constraint:
	 *     (
	 *         name='Boolean' | 
	 *         name='Integer' | 
	 *         name='Real' | 
	 *         name='String' | 
	 *         name='Double' | 
	 *         name='UnlimitedNatural' | 
	 *         name='Date' | 
	 *         name='void' | 
	 *         name='int' | 
	 *         name='boolean' | 
	 *         name='double'
	 *     )
	 */
	protected void sequence_PrimitiveType(ISerializationContext context, PrimitiveType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Type returns ReferType
	 *     ReferType returns ReferType
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_ReferType(ISerializationContext context, ReferType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ClassDiagramPackage.Literals.TYPE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ClassDiagramPackage.Literals.TYPE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getReferTypeAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AbstractElement returns Relationship
	 *     Relationship returns Relationship
	 *
	 * Constraint:
	 *     (
	 *         left=[Class|FQN] 
	 *         leftCardinality=Multiplicity? 
	 *         leftDecorator=LineDecorator? 
	 *         line=Line 
	 *         rightDecorator=LineDecorator? 
	 *         rightCardinality=Multiplicity? 
	 *         right=[Class|FQN] 
	 *         label=Label?
	 *     )
	 */
	protected void sequence_Relationship(ISerializationContext context, Relationship semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
