/*
 * generated by Xtext 2.25.0
 */
grammar InternalClassDiagram;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package com.rm2pt.rapidood.cd.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package com.rm2pt.rapidood.cd.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import com.rm2pt.rapidood.cd.services.ClassDiagramGrammarAccess;

}

@parser::members {

 	private ClassDiagramGrammarAccess grammarAccess;

    public InternalClassDiagramParser(TokenStream input, ClassDiagramGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "ClassDiagram";
   	}

   	@Override
   	protected ClassDiagramGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleClassDiagram
entryRuleClassDiagram returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getClassDiagramRule()); }
	iv_ruleClassDiagram=ruleClassDiagram
	{ $current=$iv_ruleClassDiagram.current; }
	EOF;

// Rule ClassDiagram
ruleClassDiagram returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getClassDiagramAccess().getClassDiagramAction_0(),
					$current);
			}
		)
		otherlv_1='@startuml'
		{
			newLeafNode(otherlv_1, grammarAccess.getClassDiagramAccess().getStartumlKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getClassDiagramAccess().getElementsAbstractElementParserRuleCall_2_0());
				}
				lv_elements_2_0=ruleAbstractElement
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getClassDiagramRule());
					}
					add(
						$current,
						"elements",
						lv_elements_2_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.AbstractElement");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_3='@enduml'
		{
			newLeafNode(otherlv_3, grammarAccess.getClassDiagramAccess().getEndumlKeyword_3());
		}
	)
;

// Entry rule entryRuleAbstractElement
entryRuleAbstractElement returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAbstractElementRule()); }
	iv_ruleAbstractElement=ruleAbstractElement
	{ $current=$iv_ruleAbstractElement.current; }
	EOF;

// Rule AbstractElement
ruleAbstractElement returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getAbstractElementAccess().getPackageDeclarationParserRuleCall_0());
		}
		this_PackageDeclaration_0=rulePackageDeclaration
		{
			$current = $this_PackageDeclaration_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAbstractElementAccess().getClassParserRuleCall_1());
		}
		this_Class_1=ruleClass
		{
			$current = $this_Class_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAbstractElementAccess().getInterfaceParserRuleCall_2());
		}
		this_Interface_2=ruleInterface
		{
			$current = $this_Interface_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAbstractElementAccess().getAbstractClassParserRuleCall_3());
		}
		this_AbstractClass_3=ruleAbstractClass
		{
			$current = $this_AbstractClass_3.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAbstractElementAccess().getRelationshipParserRuleCall_4());
		}
		this_Relationship_4=ruleRelationship
		{
			$current = $this_Relationship_4.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAbstractElementAccess().getEnumParserRuleCall_5());
		}
		this_Enum_5=ruleEnum
		{
			$current = $this_Enum_5.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRulePackageDeclaration
entryRulePackageDeclaration returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPackageDeclarationRule()); }
	iv_rulePackageDeclaration=rulePackageDeclaration
	{ $current=$iv_rulePackageDeclaration.current; }
	EOF;

// Rule PackageDeclaration
rulePackageDeclaration returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='package'
		{
			newLeafNode(otherlv_0, grammarAccess.getPackageDeclarationAccess().getPackageKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPackageDeclarationAccess().getNameFQNParserRuleCall_1_0());
				}
				lv_name_1_0=ruleFQN
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPackageDeclarationRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.FQN");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getPackageDeclarationAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPackageDeclarationAccess().getElementsAbstractElementParserRuleCall_3_0());
				}
				lv_elements_3_0=ruleAbstractElement
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPackageDeclarationRule());
					}
					add(
						$current,
						"elements",
						lv_elements_3_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.AbstractElement");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_4='}'
		{
			newLeafNode(otherlv_4, grammarAccess.getPackageDeclarationAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleFQN
entryRuleFQN returns [String current=null]:
	{ newCompositeNode(grammarAccess.getFQNRule()); }
	iv_ruleFQN=ruleFQN
	{ $current=$iv_ruleFQN.current.getText(); }
	EOF;

// Rule FQN
ruleFQN returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_ID_0=RULE_ID
		{
			$current.merge(this_ID_0);
		}
		{
			newLeafNode(this_ID_0, grammarAccess.getFQNAccess().getIDTerminalRuleCall_0());
		}
		(
			(
				('.')=>
				kw='.'
				{
					$current.merge(kw);
					newLeafNode(kw, grammarAccess.getFQNAccess().getFullStopKeyword_1_0());
				}
			)
			this_ID_2=RULE_ID
			{
				$current.merge(this_ID_2);
			}
			{
				newLeafNode(this_ID_2, grammarAccess.getFQNAccess().getIDTerminalRuleCall_1_1());
			}
		)*
	)
;

// Entry rule entryRuleClass
entryRuleClass returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getClassRule()); }
	iv_ruleClass=ruleClass
	{ $current=$iv_ruleClass.current; }
	EOF;

// Rule Class
ruleClass returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='class'
		{
			newLeafNode(otherlv_0, grammarAccess.getClassAccess().getClassKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getClassAccess().getNameSimpleNameParserRuleCall_1_0());
				}
				lv_name_1_0=ruleSimpleName
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getClassRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.SimpleName");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getClassAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getClassAccess().getAttributesAttributeParserRuleCall_3_0());
				}
				lv_attributes_3_0=ruleAttribute
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getClassRule());
					}
					add(
						$current,
						"attributes",
						lv_attributes_3_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Attribute");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getClassAccess().getOperationsOperationParserRuleCall_4_0());
				}
				lv_operations_4_0=ruleOperation
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getClassRule());
					}
					add(
						$current,
						"operations",
						lv_operations_4_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Operation");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getClassAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleInterface
entryRuleInterface returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getInterfaceRule()); }
	iv_ruleInterface=ruleInterface
	{ $current=$iv_ruleInterface.current; }
	EOF;

// Rule Interface
ruleInterface returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='interface'
		{
			newLeafNode(otherlv_0, grammarAccess.getInterfaceAccess().getInterfaceKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getInterfaceAccess().getNameSimpleNameParserRuleCall_1_0());
				}
				lv_name_1_0=ruleSimpleName
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getInterfaceRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.SimpleName");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getInterfaceAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getInterfaceAccess().getAttributesAttributeParserRuleCall_3_0());
				}
				lv_attributes_3_0=ruleAttribute
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getInterfaceRule());
					}
					add(
						$current,
						"attributes",
						lv_attributes_3_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Attribute");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getInterfaceAccess().getOperationsOperationParserRuleCall_4_0());
				}
				lv_operations_4_0=ruleOperation
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getInterfaceRule());
					}
					add(
						$current,
						"operations",
						lv_operations_4_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Operation");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getInterfaceAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleAbstractClass
entryRuleAbstractClass returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAbstractClassRule()); }
	iv_ruleAbstractClass=ruleAbstractClass
	{ $current=$iv_ruleAbstractClass.current; }
	EOF;

// Rule AbstractClass
ruleAbstractClass returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='abstract'
		{
			newLeafNode(otherlv_0, grammarAccess.getAbstractClassAccess().getAbstractKeyword_0());
		}
		(
			otherlv_1='class'
			{
				newLeafNode(otherlv_1, grammarAccess.getAbstractClassAccess().getClassKeyword_1());
			}
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getAbstractClassAccess().getNameSimpleNameParserRuleCall_2_0());
				}
				lv_name_2_0=ruleSimpleName
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.SimpleName");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getAbstractClassAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAbstractClassAccess().getAttributesAttributeParserRuleCall_4_0());
				}
				lv_attributes_4_0=ruleAttribute
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassRule());
					}
					add(
						$current,
						"attributes",
						lv_attributes_4_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Attribute");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getAbstractClassAccess().getOperationsOperationParserRuleCall_5_0());
				}
				lv_operations_5_0=ruleOperation
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractClassRule());
					}
					add(
						$current,
						"operations",
						lv_operations_5_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Operation");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_6='}'
		{
			newLeafNode(otherlv_6, grammarAccess.getAbstractClassAccess().getRightCurlyBracketKeyword_6());
		}
	)
;

// Entry rule entryRuleSimpleName
entryRuleSimpleName returns [String current=null]@init {
	HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
}:
	{ newCompositeNode(grammarAccess.getSimpleNameRule()); }
	iv_ruleSimpleName=ruleSimpleName
	{ $current=$iv_ruleSimpleName.current.getText(); }
	EOF;
finally {
	myHiddenTokenState.restore();
}

// Rule SimpleName
ruleSimpleName returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
	HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
}
@after {
	leaveRule();
}:
	this_ID_0=RULE_ID
	{
		$current.merge(this_ID_0);
	}
	{
		newLeafNode(this_ID_0, grammarAccess.getSimpleNameAccess().getIDTerminalRuleCall());
	}
;
finally {
	myHiddenTokenState.restore();
}

// Entry rule entryRuleAttribute
entryRuleAttribute returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAttributeRule()); }
	iv_ruleAttribute=ruleAttribute
	{ $current=$iv_ruleAttribute.current; }
	EOF;

// Rule Attribute
ruleAttribute returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getAttributeAccess().getVisibilityVisibilityParserRuleCall_0_0());
				}
				lv_visibility_0_0=ruleVisibility
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAttributeRule());
					}
					set(
						$current,
						"visibility",
						lv_visibility_0_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Visibility");
					afterParserOrEnumRuleCall();
				}
			)
		)?
		(
			(
				lv_isStatic_1_0='{static}'
				{
					newLeafNode(lv_isStatic_1_0, grammarAccess.getAttributeAccess().getIsStaticStaticKeyword_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAttributeRule());
					}
					setWithLastConsumed($current, "isStatic", lv_isStatic_1_0 != null, "{static}");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getAttributeAccess().getNameSimpleNameParserRuleCall_2_0());
				}
				lv_name_2_0=ruleSimpleName
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAttributeRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.SimpleName");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3=':'
		{
			newLeafNode(otherlv_3, grammarAccess.getAttributeAccess().getColonKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAttributeAccess().getTypeTypeParserRuleCall_4_0());
				}
				lv_type_4_0=ruleType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAttributeRule());
					}
					set(
						$current,
						"type",
						lv_type_4_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Type");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleOperation
entryRuleOperation returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getOperationRule()); }
	iv_ruleOperation=ruleOperation
	{ $current=$iv_ruleOperation.current; }
	EOF;

// Rule Operation
ruleOperation returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getOperationAccess().getVisibilityVisibilityParserRuleCall_0_0());
				}
				lv_visibility_0_0=ruleVisibility
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getOperationRule());
					}
					set(
						$current,
						"visibility",
						lv_visibility_0_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Visibility");
					afterParserOrEnumRuleCall();
				}
			)
		)?
		(
			(
				lv_isAbstract_1_0='{abstract}'
				{
					newLeafNode(lv_isAbstract_1_0, grammarAccess.getOperationAccess().getIsAbstractAbstractKeyword_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getOperationRule());
					}
					setWithLastConsumed($current, "isAbstract", lv_isAbstract_1_0 != null, "{abstract}");
				}
			)
		)?
		(
			(
				lv_isStatic_2_0='{static}'
				{
					newLeafNode(lv_isStatic_2_0, grammarAccess.getOperationAccess().getIsStaticStaticKeyword_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getOperationRule());
					}
					setWithLastConsumed($current, "isStatic", lv_isStatic_2_0 != null, "{static}");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getOperationAccess().getNameSimpleNameParserRuleCall_3_0());
				}
				lv_name_3_0=ruleSimpleName
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getOperationRule());
					}
					set(
						$current,
						"name",
						lv_name_3_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.SimpleName");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='('
		{
			newLeafNode(otherlv_4, grammarAccess.getOperationAccess().getLeftParenthesisKeyword_4());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getOperationAccess().getParamsParameterParserRuleCall_5_0_0());
					}
					lv_params_5_0=ruleParameter
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getOperationRule());
						}
						add(
							$current,
							"params",
							lv_params_5_0,
							"com.rm2pt.rapidood.cd.ClassDiagram.Parameter");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_6=','
				{
					newLeafNode(otherlv_6, grammarAccess.getOperationAccess().getCommaKeyword_5_1_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getOperationAccess().getParamsParameterParserRuleCall_5_1_1_0());
						}
						lv_params_7_0=ruleParameter
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getOperationRule());
							}
							add(
								$current,
								"params",
								lv_params_7_0,
								"com.rm2pt.rapidood.cd.ClassDiagram.Parameter");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_8=')'
		{
			newLeafNode(otherlv_8, grammarAccess.getOperationAccess().getRightParenthesisKeyword_6());
		}
		otherlv_9=':'
		{
			newLeafNode(otherlv_9, grammarAccess.getOperationAccess().getColonKeyword_7());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getOperationAccess().getReturnTypeTypeParserRuleCall_8_0());
				}
				lv_returnType_10_0=ruleType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getOperationRule());
					}
					set(
						$current,
						"returnType",
						lv_returnType_10_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Type");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleParameter
entryRuleParameter returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getParameterRule()); }
	iv_ruleParameter=ruleParameter
	{ $current=$iv_ruleParameter.current; }
	EOF;

// Rule Parameter
ruleParameter returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getParameterAccess().getTypeTypeParserRuleCall_0_0());
				}
				lv_type_0_0=ruleType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getParameterRule());
					}
					set(
						$current,
						"type",
						lv_type_0_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Type");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getParameterAccess().getNameSimpleNameParserRuleCall_1_0());
				}
				lv_name_1_0=ruleSimpleName
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getParameterRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.SimpleName");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleVisibility
entryRuleVisibility returns [String current=null]:
	{ newCompositeNode(grammarAccess.getVisibilityRule()); }
	iv_ruleVisibility=ruleVisibility
	{ $current=$iv_ruleVisibility.current.getText(); }
	EOF;

// Rule Visibility
ruleVisibility returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='+'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getVisibilityAccess().getPlusSignKeyword_0());
		}
		    |
		kw='-'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getVisibilityAccess().getHyphenMinusKeyword_1());
		}
		    |
		kw='#'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getVisibilityAccess().getNumberSignKeyword_2());
		}
		    |
		kw='~'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getVisibilityAccess().getTildeKeyword_3());
		}
	)
;

// Entry rule entryRuleRelationship
entryRuleRelationship returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRelationshipRule()); }
	iv_ruleRelationship=ruleRelationship
	{ $current=$iv_ruleRelationship.current; }
	EOF;

// Rule Relationship
ruleRelationship returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getRelationshipAccess().getRelationshipAction_0(),
					$current);
			}
		)
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRelationshipRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getRelationshipAccess().getLeftClassCrossReference_1_0());
				}
				ruleFQN
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getRelationshipAccess().getLeftCardinalityMultiplicityParserRuleCall_2_0());
				}
				lv_leftCardinality_2_0=ruleMultiplicity
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRelationshipRule());
					}
					set(
						$current,
						"leftCardinality",
						lv_leftCardinality_2_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Multiplicity");
					afterParserOrEnumRuleCall();
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getRelationshipAccess().getLeftDecoratorLineDecoratorParserRuleCall_3_0());
				}
				lv_leftDecorator_3_0=ruleLineDecorator
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRelationshipRule());
					}
					set(
						$current,
						"leftDecorator",
						lv_leftDecorator_3_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.LineDecorator");
					afterParserOrEnumRuleCall();
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getRelationshipAccess().getLineLineParserRuleCall_4_0());
				}
				lv_line_4_0=ruleLine
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRelationshipRule());
					}
					set(
						$current,
						"line",
						lv_line_4_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Line");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getRelationshipAccess().getRightDecoratorLineDecoratorParserRuleCall_5_0());
				}
				lv_rightDecorator_5_0=ruleLineDecorator
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRelationshipRule());
					}
					set(
						$current,
						"rightDecorator",
						lv_rightDecorator_5_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.LineDecorator");
					afterParserOrEnumRuleCall();
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getRelationshipAccess().getRightCardinalityMultiplicityParserRuleCall_6_0());
				}
				lv_rightCardinality_6_0=ruleMultiplicity
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRelationshipRule());
					}
					set(
						$current,
						"rightCardinality",
						lv_rightCardinality_6_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.Multiplicity");
					afterParserOrEnumRuleCall();
				}
			)
		)?
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRelationshipRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getRelationshipAccess().getRightClassCrossReference_7_0());
				}
				ruleFQN
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_8=':'
			{
				newLeafNode(otherlv_8, grammarAccess.getRelationshipAccess().getColonKeyword_8_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getRelationshipAccess().getLabelLabelParserRuleCall_8_1_0());
					}
					lv_label_9_0=ruleLabel
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getRelationshipRule());
						}
						set(
							$current,
							"label",
							lv_label_9_0,
							"com.rm2pt.rapidood.cd.ClassDiagram.Label");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
	)
;

// Entry rule entryRuleMultiplicity
entryRuleMultiplicity returns [String current=null]:
	{ newCompositeNode(grammarAccess.getMultiplicityRule()); }
	iv_ruleMultiplicity=ruleMultiplicity
	{ $current=$iv_ruleMultiplicity.current.getText(); }
	EOF;

// Rule Multiplicity
ruleMultiplicity returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	this_DOUBLE_QUOTED_STRING_0=RULE_DOUBLE_QUOTED_STRING
	{
		$current.merge(this_DOUBLE_QUOTED_STRING_0);
	}
	{
		newLeafNode(this_DOUBLE_QUOTED_STRING_0, grammarAccess.getMultiplicityAccess().getDOUBLE_QUOTED_STRINGTerminalRuleCall());
	}
;

// Entry rule entryRuleLineDecorator
entryRuleLineDecorator returns [String current=null]:
	{ newCompositeNode(grammarAccess.getLineDecoratorRule()); }
	iv_ruleLineDecorator=ruleLineDecorator
	{ $current=$iv_ruleLineDecorator.current.getText(); }
	EOF;

// Rule LineDecorator
ruleLineDecorator returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='<|'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getLineDecoratorAccess().getLessThanSignVerticalLineKeyword_0());
		}
		    |
		kw='|>'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getLineDecoratorAccess().getVerticalLineGreaterThanSignKeyword_1());
		}
		    |
		kw='o'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getLineDecoratorAccess().getOKeyword_2());
		}
		    |
		kw='*'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getLineDecoratorAccess().getAsteriskKeyword_3());
		}
		    |
		kw='<'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getLineDecoratorAccess().getLessThanSignKeyword_4());
		}
		    |
		kw='>'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getLineDecoratorAccess().getGreaterThanSignKeyword_5());
		}
	)
;

// Entry rule entryRuleLine
entryRuleLine returns [String current=null]:
	{ newCompositeNode(grammarAccess.getLineRule()); }
	iv_ruleLine=ruleLine
	{ $current=$iv_ruleLine.current.getText(); }
	EOF;

// Rule Line
ruleLine returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='--'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getLineAccess().getHyphenMinusHyphenMinusKeyword_0());
		}
		    |
		kw='-'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getLineAccess().getHyphenMinusKeyword_1());
		}
		    |
		kw='..'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getLineAccess().getFullStopFullStopKeyword_2());
		}
		    |
		kw='.'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getLineAccess().getFullStopKeyword_3());
		}
	)
;

// Entry rule entryRuleLabel
entryRuleLabel returns [String current=null]:
	{ newCompositeNode(grammarAccess.getLabelRule()); }
	iv_ruleLabel=ruleLabel
	{ $current=$iv_ruleLabel.current.getText(); }
	EOF;

// Rule Label
ruleLabel returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_ID_0=RULE_ID
		{
			$current.merge(this_ID_0);
		}
		{
			newLeafNode(this_ID_0, grammarAccess.getLabelAccess().getIDTerminalRuleCall());
		}
	)+
;

// Entry rule entryRuleType
entryRuleType returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTypeRule()); }
	iv_ruleType=ruleType
	{ $current=$iv_ruleType.current; }
	EOF;

// Rule Type
ruleType returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getTypeAccess().getPrimitiveTypeParserRuleCall_0());
		}
		this_PrimitiveType_0=rulePrimitiveType
		{
			$current = $this_PrimitiveType_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getTypeAccess().getReferTypeParserRuleCall_1());
		}
		this_ReferType_1=ruleReferType
		{
			$current = $this_ReferType_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRulePrimitiveType
entryRulePrimitiveType returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPrimitiveTypeRule()); }
	iv_rulePrimitiveType=rulePrimitiveType
	{ $current=$iv_rulePrimitiveType.current; }
	EOF;

// Rule PrimitiveType
rulePrimitiveType returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_name_0_1='Boolean'
				{
					newLeafNode(lv_name_0_1, grammarAccess.getPrimitiveTypeAccess().getNameBooleanKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_1, null);
				}
				    |
				lv_name_0_2='Integer'
				{
					newLeafNode(lv_name_0_2, grammarAccess.getPrimitiveTypeAccess().getNameIntegerKeyword_0_1());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_2, null);
				}
				    |
				lv_name_0_3='Real'
				{
					newLeafNode(lv_name_0_3, grammarAccess.getPrimitiveTypeAccess().getNameRealKeyword_0_2());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_3, null);
				}
				    |
				lv_name_0_4='String'
				{
					newLeafNode(lv_name_0_4, grammarAccess.getPrimitiveTypeAccess().getNameStringKeyword_0_3());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_4, null);
				}
				    |
				lv_name_0_5='Double'
				{
					newLeafNode(lv_name_0_5, grammarAccess.getPrimitiveTypeAccess().getNameDoubleKeyword_0_4());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_5, null);
				}
				    |
				lv_name_0_6='UnlimitedNatural'
				{
					newLeafNode(lv_name_0_6, grammarAccess.getPrimitiveTypeAccess().getNameUnlimitedNaturalKeyword_0_5());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_6, null);
				}
				    |
				lv_name_0_7='Date'
				{
					newLeafNode(lv_name_0_7, grammarAccess.getPrimitiveTypeAccess().getNameDateKeyword_0_6());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_7, null);
				}
				    |
				lv_name_0_8='void'
				{
					newLeafNode(lv_name_0_8, grammarAccess.getPrimitiveTypeAccess().getNameVoidKeyword_0_7());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_8, null);
				}
				    |
				lv_name_0_9='int'
				{
					newLeafNode(lv_name_0_9, grammarAccess.getPrimitiveTypeAccess().getNameIntKeyword_0_8());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_9, null);
				}
				    |
				lv_name_0_10='boolean'
				{
					newLeafNode(lv_name_0_10, grammarAccess.getPrimitiveTypeAccess().getNameBooleanKeyword_0_9());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_10, null);
				}
				    |
				lv_name_0_11='double'
				{
					newLeafNode(lv_name_0_11, grammarAccess.getPrimitiveTypeAccess().getNameDoubleKeyword_0_10());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPrimitiveTypeRule());
					}
					setWithLastConsumed($current, "name", lv_name_0_11, null);
				}
			)
		)
	)
;

// Entry rule entryRuleReferType
entryRuleReferType returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getReferTypeRule()); }
	iv_ruleReferType=ruleReferType
	{ $current=$iv_ruleReferType.current; }
	EOF;

// Rule ReferType
ruleReferType returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			lv_name_0_0=RULE_ID
			{
				newLeafNode(lv_name_0_0, grammarAccess.getReferTypeAccess().getNameIDTerminalRuleCall_0());
			}
			{
				if ($current==null) {
					$current = createModelElement(grammarAccess.getReferTypeRule());
				}
				setWithLastConsumed(
					$current,
					"name",
					lv_name_0_0,
					"org.eclipse.xtext.common.Terminals.ID");
			}
		)
	)
;

// Entry rule entryRuleEnumItem
entryRuleEnumItem returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEnumItemRule()); }
	iv_ruleEnumItem=ruleEnumItem
	{ $current=$iv_ruleEnumItem.current; }
	EOF;

// Rule EnumItem
ruleEnumItem returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getEnumItemAccess().getNameSimpleNameParserRuleCall_0());
			}
			lv_name_0_0=ruleSimpleName
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getEnumItemRule());
				}
				set(
					$current,
					"name",
					lv_name_0_0,
					"com.rm2pt.rapidood.cd.ClassDiagram.SimpleName");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleEnum
entryRuleEnum returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEnumRule()); }
	iv_ruleEnum=ruleEnum
	{ $current=$iv_ruleEnum.current; }
	EOF;

// Rule Enum
ruleEnum returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getEnumAccess().getEnumAction_0(),
					$current);
			}
		)
		otherlv_1='enum'
		{
			newLeafNode(otherlv_1, grammarAccess.getEnumAccess().getEnumKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getEnumAccess().getNameSimpleNameParserRuleCall_2_0());
				}
				lv_name_2_0=ruleSimpleName
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getEnumRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"com.rm2pt.rapidood.cd.ClassDiagram.SimpleName");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getEnumAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getEnumAccess().getValuesEnumItemParserRuleCall_4_0_0());
					}
					lv_values_4_0=ruleEnumItem
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getEnumRule());
						}
						add(
							$current,
							"values",
							lv_values_4_0,
							"com.rm2pt.rapidood.cd.ClassDiagram.EnumItem");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getEnumAccess().getValuesEnumItemParserRuleCall_4_1_0());
					}
					lv_values_5_0=ruleEnumItem
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getEnumRule());
						}
						add(
							$current,
							"values",
							lv_values_5_0,
							"com.rm2pt.rapidood.cd.ClassDiagram.EnumItem");
						afterParserOrEnumRuleCall();
					}
				)
			)*
		)
		otherlv_6='}'
		{
			newLeafNode(otherlv_6, grammarAccess.getEnumAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

RULE_DOUBLE_QUOTED_STRING : '"' (RULE_ESCAPED_CHARACTER|~(('\\'|'"'|'.')))* '"';

fragment RULE_ESCAPED_CHARACTER : '\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|'\''|'\\');

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
