/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import com.rm2pt.rapidood.cd.classDiagram.Class
import com.rm2pt.rapidood.cd.classDiagram.Relationship
import com.rm2pt.rapidood.cd.classDiagram.ClassDiagram
import org.eclipse.xtext.resource.XtextResource
import com.google.inject.Injector
import com.rm2pt.rapidood.cd.ClassDiagramStandaloneSetup
import org.eclipse.emf.ecore.resource.ResourceSet
import java.util.Collections
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.eclipse.xtext.formatting2.AbstractFormatter2
import com.rm2pt.rapidood.cd.services.ClassDiagramGrammarAccess
import com.google.inject.Inject
import org.eclipse.xtext.formatting2.regionaccess.TextRegionAccessBuilder
import com.rm2pt.rapidood.cd.formatting2.ClassDiagramFormatter
import com.rm2pt.rapidood.cd.classDiagram.ClassDiagramFactory

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class ClassDiagramGenerator extends AbstractGenerator{
	@Inject extension ClassDiagramGrammarAccess
	@Inject ClassDiagramFormatter classDiagramFormatter
	static Injector injector;
	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		
		fsa.generateFile('ClassDiagramWithEntityManager.cd', resource.originalContent)
		val tempUri = fsa.getURI("ClassDiagramWithEntityManager.cd")
		val resourceSet = getInjector().getInstance(ResourceSet)
		val tempResource = resourceSet.getResource(tempUri, true) as XtextResource
		tempResource.load(Collections.emptyMap())
	
	}
	
	
	def static synchronized Injector getInjector() {
		if (injector == null) {
            injector = new ClassDiagramStandaloneSetup().createInjectorAndDoEMFRegistration();
        }
        return injector;
	}

	def getOriginalContent(Resource resource) {
		if (resource instanceof XtextResource) {
			val xtextResource = resource as XtextResource
		 	val parseResult = xtextResource.parseResult
		 	if (parseResult !== null) {
	            val rootNode = parseResult.rootNode
	            val textContent = rootNode.text
	            return textContent
       		} else {
            	println("解析失败：AST未生成")
        	}
        } else {
        	println("非Xtext资源类型: " + resource?.class?.simpleName)
        } 
	}

}

