/**
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.sd.generator;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class SequenceDiagramGenerator extends AbstractGenerator {
  private static List<EObject> ends = new ArrayList<EObject>();
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type SequenceDiagramStandaloneSetup"
      + "\ngetInstance cannot be resolved");
  }
  
  public void enhanceModel(final Resource resource) {
    throw new Error("Unresolved compilation problems:"
      + "\nSequenceDiagram cannot be resolved to a type."
      + "\nThe method generateEnds(SequenceDiagram) from the type SequenceDiagramGenerator refers to the missing type SequenceDiagram"
      + "\nThe method generateExecutions(SequenceDiagram) from the type SequenceDiagramGenerator refers to the missing type SequenceDiagram");
  }
  
  public void generateEnds(final /* SequenceDiagram */Object sd) {
    throw new Error("Unresolved compilation problems:"
      + "\nMessage cannot be resolved to a type."
      + "\nMessage cannot be resolved to a type."
      + "\nActivation cannot be resolved to a type."
      + "\nActivation cannot be resolved to a type."
      + "\nDeactivation cannot be resolved to a type."
      + "\nDeactivation cannot be resolved to a type."
      + "\nThe method or field SequenceDiagramFactory is undefined"
      + "\nThe method or field SequenceDiagramFactory is undefined"
      + "\nThe method or field arrow is undefined for the type EObject"
      + "\nThe method or field SequenceDiagramFactory is undefined"
      + "\nThe method or field arrow is undefined for the type EObject"
      + "\nThe method or field SequenceDiagramFactory is undefined"
      + "\nThe method or field SequenceDiagramFactory is undefined"
      + "\nThe method or field SequenceDiagramFactory is undefined"
      + "\nUnreachable code: The if condition can never match. It is already handled by a previous condition."
      + "\nUnreachable code: The if condition can never match. It is already handled by a previous condition."
      + "\neContents cannot be resolved"
      + "\neINSTANCE cannot be resolved"
      + "\ncreateMessageEnd cannot be resolved"
      + "\neINSTANCE cannot be resolved"
      + "\ncreateMessageEnd cannot be resolved"
      + "\nSYNC cannot be resolved"
      + "\n!== cannot be resolved"
      + "\neINSTANCE cannot be resolved"
      + "\ncreateCallMessage cannot be resolved"
      + "\ndescription cannot be resolved"
      + "\ndescription cannot be resolved"
      + "\nsendingEnd cannot be resolved"
      + "\nreceivingEnd cannot be resolved"
      + "\nname cannot be resolved"
      + "\nmessage cannot be resolved"
      + "\nmessage cannot be resolved"
      + "\nmessages cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nRETURN cannot be resolved"
      + "\n!== cannot be resolved"
      + "\neINSTANCE cannot be resolved"
      + "\ncreateReturnMessage cannot be resolved"
      + "\ndescription cannot be resolved"
      + "\ndescription cannot be resolved"
      + "\nsendingEnd cannot be resolved"
      + "\nreceivingEnd cannot be resolved"
      + "\nname cannot be resolved"
      + "\nmessage cannot be resolved"
      + "\nmessage cannot be resolved"
      + "\nmessages cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nsetContext cannot be resolved"
      + "\ngetSender cannot be resolved"
      + "\nsetName cannot be resolved"
      + "\nends cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nsetContext cannot be resolved"
      + "\ngetReceiver cannot be resolved"
      + "\nsetName cannot be resolved"
      + "\nends cannot be resolved"
      + "\nadd cannot be resolved"
      + "\neINSTANCE cannot be resolved"
      + "\ncreateExecutionStart cannot be resolved"
      + "\nsetContext cannot be resolved"
      + "\ngetContext cannot be resolved"
      + "\nends cannot be resolved"
      + "\nadd cannot be resolved"
      + "\neINSTANCE cannot be resolved"
      + "\ncreateExecutionEnd cannot be resolved"
      + "\nsetContext cannot be resolved"
      + "\ngetContext cannot be resolved"
      + "\nends cannot be resolved"
      + "\nadd cannot be resolved");
  }
  
  public void generateExecutions(final /* SequenceDiagram */Object sd) {
    throw new Error("Unresolved compilation problems:"
      + "\nMultiContext cannot be resolved to a type."
      + "\nMixEnd cannot be resolved to a type."
      + "\nMixEnd cannot be resolved to a type."
      + "\nExecutionStart cannot be resolved to a type."
      + "\nMixEnd cannot be resolved to a type."
      + "\nExecutionEnd cannot be resolved to a type."
      + "\nMixEnd cannot be resolved to a type."
      + "\nExecutionStart cannot be resolved to a type."
      + "\nMixEnd cannot be resolved to a type."
      + "\nExecutionEnd cannot be resolved to a type."
      + "\nExecutionStart cannot be resolved to a type."
      + "\nExecutionEnd cannot be resolved to a type."
      + "\nParticipant cannot be resolved to a type."
      + "\nExecutionStart cannot be resolved to a type."
      + "\nExecutionEnd cannot be resolved to a type."
      + "\nExecutionStart cannot be resolved to a type."
      + "\nExecutionEnd cannot be resolved to a type."
      + "\nThe method or field SequenceDiagramFactory is undefined"
      + "\nUnreachable code: The if condition can never match. It is already handled by a previous condition."
      + "\ngetContext cannot be resolved"
      + "\ngetContext cannot be resolved"
      + "\ngetContext cannot be resolved"
      + "\ngetContext cannot be resolved"
      + "\ngetContext cannot be resolved"
      + "\ngetContext cannot be resolved"
      + "\neINSTANCE cannot be resolved"
      + "\ncreateExecution cannot be resolved"
      + "\nsetStart cannot be resolved"
      + "\nsetEnd cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ngetContext cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\ngetContext cannot be resolved"
      + "\nsetOwner cannot be resolved"
      + "\nsetName cannot be resolved"
      + "\nexecutions cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nsetContext cannot be resolved"
      + "\nsetContext cannot be resolved"
      + "\nsetExecution cannot be resolved"
      + "\nsetName cannot be resolved"
      + "\nsetExecution cannot be resolved"
      + "\nsetName cannot be resolved"
      + "\nsetContext cannot be resolved"
      + "\nsetContext cannot be resolved");
  }
}
