/*
 * generated by Xtext 2.25.0
 */
package com.rm2pt.rapidood.cd.formatting2

import com.google.inject.Inject
import com.rm2pt.rapidood.cd.classDiagram.ClassDiagram
import com.rm2pt.rapidood.cd.classDiagram.PackageDeclaration
import com.rm2pt.rapidood.cd.classDiagram.Class
import com.rm2pt.rapidood.cd.services.ClassDiagramGrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import com.rm2pt.rapidood.cd.classDiagram.Attribute
import com.rm2pt.rapidood.cd.classDiagram.Enum
import static com.rm2pt.rapidood.cd.classDiagram.ClassDiagramPackage.Literals.*
import com.rm2pt.rapidood.cd.classDiagram.Relationship
import com.rm2pt.rapidood.cd.classDiagram.EnumItem
import org.eclipse.emf.ecore.resource.Resource
import com.rm2pt.rapidood.cd.classDiagram.Operation

class ClassDiagramFormatter extends AbstractFormatter2 {
	
	@Inject extension ClassDiagramGrammarAccess

	def dispatch void format(ClassDiagram classDiagram, extension IFormattableDocument document) {
		val start = classDiagram.regionFor.keyword("@startuml");
        start.append[setNewLines(1)]
        val end = classDiagram.regionFor.keyword("@enduml");
        end.prepend[setNewLines(1)]
		for (abstractElement : classDiagram.elements) {
			abstractElement.format
		}
	}

	def dispatch void format(PackageDeclaration packageDeclaration, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		
		val start = packageDeclaration.regionFor.keyword("{");
		start.append[setNewLines(1)]
		val end = packageDeclaration.regionFor.keyword("}");
		end.prepend[setNewLines(1)]
		end.append[newLine]
		interior(start, end)[indent]
		for (abstractElement : packageDeclaration.elements) {
			abstractElement.format
		}
	}
	
	// TODO: implement for Class, Interface, AbstractClass, Attribute, Operation, Parameter, Enum
	def dispatch void format(Class clz, extension IFormattableDocument document) {
		val start = clz.regionFor.keyword("{")
		start.append[setNewLines(1)]
		val end = clz.regionFor.keyword("}")
		end.prepend[setNewLines(1)]
		end.append[newLine]
		interior(start, end)[indent]
		for (attribute : clz.attributes) {
			attribute.format
		}
		for (operation : clz.operations) {
			operation.format
		}
	}
	
	def dispatch void format(Attribute attr, extension IFormattableDocument document) {
//		val lastRegion = attr.regionFor.feature(ATTRIBUTE__TYPE)
//		lastRegion.append[noSpace]
//		lastRegion.append[newLine]
		attr.append[newLine]
	}
	
	def dispatch void format(Operation op, extension IFormattableDocument document) {
		op.append[newLine]
	}
	
	def dispatch void format(Enum enu, extension IFormattableDocument document) {
		val start = enu.regionFor.keyword("{")
		start.append[newLine]
		val end = enu.regionFor.keyword("}")
		end.prepend[newLine]
		interior(start, end)[indent]
		enu.append[newLine]
		for (enumItem : enu.values) {
			enumItem.format
		}
	}
	
	def dispatch void format(EnumItem enumItem, extension IFormattableDocument document) {
		enumItem.append[newLine]
	}
	
	def dispatch void format(Relationship relation, extension IFormattableDocument document) {
		relation.regionFor.feature(RELATIONSHIP__LINE).surround[noSpace]
		val right = relation.regionFor.feature(RELATIONSHIP__RIGHT)
		val label = relation.regionFor.feature(RELATIONSHIP__LABEL)
		(label ?: right)?.append[newLine]
	}
	
}


